const fs = require('fs');

const generatorPath = '/Users/mohammedabunada/Documents/Vipe/snabbaLexin/generate_advanced_levels.js';
let content = fs.readFileSync(generatorPath, 'utf8');

const enhancements = {
    // Chapter 1: Food
    "LISTA": { s: "Jag måste skriva en lång lista.", st: "يجب أن أكتب قائمة طويلة." },
    "SILA": { s: "Sila mygg och svälja kameler.", st: "يصفي البعوض ويبتلع الجمال (مثل)." },
    "STIL": { s: "Jag gillar verkligen din unika stil.", st: "أنا معجب حقاً بأسلوبك الفريد." },
    "STEKA": { s: "Vi ska steka köttbullar till middag.", st: "سنقلي كرات اللحم للعشاء." },
    "KAST": { s: "Det var ett riktigt dåligt kast.", st: "كانت تلك رمية سيئة حقاً." },
    "ASK": { s: "Jag köpte en liten ask tändstickor.", st: "اشتريت علبة صغيرة من أعواد الثقاب." },
    "MATEN": { s: "Kom och ät, maten är klar!", st: "تعالوا لتناول الطعام، الأكل جاهز!" },
    "FLASKA": { s: "Kan jag få en flaska vatten?", st: "هل يمكنني الحصول على زجاجة ماء؟" },
    "FALSK": { s: "Det där skrattet låter väldigt falskt.", st: "تلك الضحكة تبدو مصطنعة جداً." },
    "SKALA": { s: "Det är lätt att skala en banan.", st: "من السهل تقشير الموزة." },
    "SALLAD": { s: "Jag vill ha en fräsch sallad.", st: "أريد سلطة طازجة." },
    "LADA": { s: "Hästen står inne i en lada.", st: "الحصان يقف داخل الحظيرة." },
    "DALA": { s: "Vi såg solen dala ner i havet.", st: "رأينا الشمس تغرب في البحر." },
    "SKEDAR": { s: "Vi behöver skedar för att äta soppa.", st: "نحتاج إلى ملاعق لتناول الحساء." },
    "DERAS": { s: "Det är deras ansvar att lösa detta.", st: "إنها مسؤوليتهم لحل هذا الأمر." },
    "KADER": { s: "En liten kader av lojala soldater.", st: "كادر صغير من الجنود المخلصين." },
    "SKADE": { s: "Det var inte menat till skada.", st: "لم يكن القصد إلحاق الأذى." },
    "FRUKOST": { s: "Frukost är dagens viktigaste måltid.", st: "الفطور هو أهم وجبة في اليوم." },
    "KORT": { s: "Livet är kort, så njut av det.", st: "الحياة قصيرة، لذا استمتع بها." },
    "STOR": { s: "Han beställde en stor stark öl.", st: "طلب كأساً كبيراً من البيرة القوية." },

    // Chapter 2: Nature
    "LOS": { s: "Vi måste kasta loss nu genast.", st: "يجب أن نفك الحبال ونبحر فوراً." },
    "HAV": { s: "Han har seglat på de sju haven.", st: "لقد أبحر في البحار السبعة." },
    "TRÄ": { s: "Det är svårt att trä nålen.", st: "من الصعب إدخال الخيط في الإبرة." },
    "STENAR": { s: "Man ska inte kasta stenar i glashus.", st: "لا ترمِ الناس بالحجارة وبيتك من زجاج." },
    "ENAR": { s: "Dessa enar är gröna året om.", st: "أشجار العرعر هذه خضراء طوال العام." },
    "RESA": { s: "Att resa är att leva, sa han.", st: "قال إن السفر هو الحياة." },
    "DALAR": { s: "Vi vandrade över berg och dal.", st: "تجولنا عبر الجبال والوديان." },
    "FLODEN": { s: "Floden rinner stilla genom staden.", st: "النهر يجري بهدوء عبر المدينة." },
    "FLOD": { s: "Tidvattnet växlar mellan ebb och flod.", st: "المد والجزر يتبادلان الأدوار." },
    "ODEN": { s: "Oden var en mäktig gud i mytologin.", st: "كان أودين إلهاً قوياً في الأساطير." },
    "TJÄRNA": { s: "Vi badade i en liten skogstjärna.", st: "سبحنا في بحيرة غابة صغيرة." },
    "RÄNTA": { s: "Ränta på ränta ger stor effekt.", st: "الفائدة المركبة تعطي تأثيراً كبيراً." },
    "TÄRNA": { s: "Hon valdes till årets Lucia tärna.", st: "تم اختيارها لتكون وصيفة لوسيا لهذا العام." },
    "BUSKAR": { s: "Katten gömde sig i buskarna.", st: "اختبأت القطة بين الشجيرات." },
    "BRUKA": { s: "Man måste bruka jorden för att skörda.", st: "يجب فلاحة الأرض للحصول على الحصاد." },
    "SKURA": { s: "Jag måste skura golvet i köket.", st: "يجب أن أفرك أرضية المطبخ." },
    "RUSA": { s: "Du behöver inte rusa iväg så fort.", st: "لا داعي للاندفاع والمغادرة بهذه السرعة." },
    "VÄDRET": { s: "Alla gillar att prata om vädret.", st: "الجميع يحب الحديث عن الطقس." },
    "VÄRDE": { s: "Detta smycke har ett högt värde.", st: "هذه المجوهرات لها قيمة عالية." },
    "TRÄDE": { s: "Åkern fick ligga i träde ett år.", st: "تُرك الحقل بوراً لمدة عام." },
    "VÄRDET": { s: "Värdet av allt vi äger är stort.", st: "قيمة كل ما نملكه كبيرة." },
    "NATUREN": { s: "Vi måste alla hjälpas åt att skydda naturen.", st: "يجب أن نتعاون جميعاً لحماية الطبيعة." },
    "NATUR": { s: "Sverige har en mycket vacker natur.", st: "تتمتع السويد بطبيعة جميلة جداً." },
    "RUNT": { s: "Han seglade jorden runt ensam.", st: "أبحر حول العالم بمفرده." },
    "TUNA": { s: "Eskilstuna är en fin gammal stad.", st: "إسكيلستونا مدينة قديمة وجميلة." },
    "RUTA": { s: "Rita en ruta på papperet.", st: "ارسم مربعاً على الورقة." },

    // Chapter 3: Travel
    "RES": { s: "Res dig upp och kämpa vidare.", st: "انهض وواصل الكفاح." },
    "GATA": { s: "Se dig för innan du går över gatan.", st: "انتبه قبل عبور الشارع." },
    "TAG": { s: "Ta ett tag i repet och dra.", st: "أمسك بالحبل واسحب." },
    "BRO": { s: "Vi körde över en lång bro.", st: "قدنا السيارة فوق جسر طويل." },
    "BOR": { s: "Var bor du någonstans nuförtiden?", st: "أين تسكن في هذه الأيام؟" },
    "RESAN": { s: "Resan var lång och mycket tröttsam.", st: "كانت الرحلة طويلة ومرهقة جداً." },
    "SENA": { s: "Jag gillar sena kvällar på sommaren.", st: "أحب الأمسيات المتأخرة في الصيف." },
    "PLATS": { s: "Var vänlig och ta plats i väntrummet.", st: "تفضل بالجلوس في غرفة الانتظار." },
    "LAST": { s: "Lastbilen hade en mycket tung last.", st: "كانت الشاحنة تحمل حمولة ثقيلة جداً." },
    "STAL": { s: "Tjuven stal cykeln mitt på dagen.", st: "سرق اللص الدراجة في وضح النهار." },
    "ÖSTER": { s: "Solen går alltid upp i öster.", st: "الشمس تشرق دائماً من الشرق." },
    "RÖST": { s: "Hon har en otroligt vacker röst.", st: "لديها صوت جميل بشكل لا يصدق." },
    "REST": { s: "Vi har rest över hela världen.", st: "لقد سافرنا حول العالم بأسره." },
    "SEGLAR": { s: "Han seglar sin båt varje sommar.", st: "يبحر بقاربه كل صيف." },
    "SEGLA": { s: "Att segla är en underbar frihetskänsla.", st: "الإبحار يمنح شعوراً رائعاً بالحرية." },
    "LAGER": { s: "Vi har varan på lager just nu.", st: "لدينا السلعة في المخزون حالياً." },
    "SEGRA": { s: "Det viktigaste är inte att segra.", st: "الأهم ليس هو الانتصار." },
    "BUSSAR": { s: "Bussarna går ofta in till centrum.", st: "تسير الحافلات غالباً إلى وسط المدينة." },
    "BRAS": { s: "Vi tände en bras i öppna spisen.", st: "أشعلنا ناراً في المدفأة." },
    "BARS": { s: "Han bars ut på bår efter olyckan.", st: "حُمل على نقالة بعد الحادث." },
    "FÄRDEN": { s: "Färden mot norr var mycket kall.", st: "كانت الرحلة نحو الشمال باردة جداً." },
    "FÄRDE": { s: "Nu är det fara å färde.", st: "الآن هناك خطر محدق." },
    "ÄNDER": { s: "Barnen gillar att mata änder i parken.", st: "يحب الأطفال إطعام البط في الحديقة." },
    "VÄRLDEN": { s: "Han vill resa runt hela världen.", st: "يريد السفر حول العالم بأسره." },
    "VÄRDE": { s: "Detta har ett stort sentimentalt värde.", st: "هذا له قيمة عاطفية كبيرة." },
    "LÄRDE": { s: "De lärde tvistar om den saken.", st: "العلماء يختلفون حول هذا الأمر." },
    "VÄRLD": { s: "Vi lever i en föränderlig värld.", st: "نحن نعيش في عالم متغير." },
    "UTLAND": { s: "Han har bott i utlandet i många år.", st: "لقد عاش في الخارج لسنوات عديدة." },
    "LAND": { s: "Sverige är ett avlångt land.", st: "السويد بلد طويل الامتداد." },
    "TAND": { s: "Jag har tappat en tand idag.", st: "لقد فقدت سناً اليوم." },
    "LUND": { s: "Vi hade picknick i en grön lund.", st: "قمنا بنزهة في بستان أخضر." },
    "LUTA": { s: "Luta dig inte ut genom fönstret.", st: "لا تمل بجسدك خارج النافذة." },

    // Chapter 4: Daily
    "RUM": { s: "Detta är mitt eget lilla rum.", st: "هذه غرفتي الصغيرة الخاصة." },
    "MUR": { s: "De byggde en hög mur runt huset.", st: "بنوا جداراً عالياً حول المنزل." },
    "HUS": { s: "Vi bor i ett litet rött hus.", st: "نعيش في منزل أحمر صغير." },
    "TAK": { s: "Taket läcker när det regnar mycket.", st: "السقف يسرب الماء عندما تمطر بغزارة." },
    "AKT": { s: "Vi såg första akten av pjäsen.", st: "شاهدنا الفصل الأول من المسرحية." },
    "STOL": { s: "Dra fram en stol och sitt ner.", st: "اسحب كرسياً واجلس." },
    "LOTS": { s: "Fartyget behövde en lots för att komma in.", st: "احتاجت السفينة إلى مرشد للدخول." },
    "SOL": { s: "Solen skiner från en klarblå himmel.", st: "الشمس تشرق من سماء زرقاء صافية." },
    "BORD": { s: "Maten står framdukad på bordet.", st: "الطعام موضوع على الطاولة." },
    "ORD": { s: "Ett ord kan säga mer än tusen bilder.", st: "كلمة واحدة قد تقول أكثر من ألف صورة." },
    "BOR": { s: "Vi bor i en lägenhet i stan.", st: "نحن نسكن في شقة في المدينة." },
    "SÄNG": { s: "Jag har en mycket mjuk och skön säng.", st: "لدي سرير ناعم ومريح جداً." },
    "ÄNG": { s: "Vi hade picknick på en blommig äng.", st: "قمنا بنزهة في مرج مليء بالزهور." },
    "DÖRRAR": { s: "Vi håller alla dörrar öppna för dig.", st: "نحن نبقي جميع الأبواب مفتوحة لك." },
    "DÖRR": { s: "Stäng dörren, det drar kallt.", st: "أغلق الباب، هناك تيار هواء بارد." },
    "RÖRA": { s: "Vilken röra du har ställt till med!", st: "يا لها من فوضى تسببت بها!" },
    "RÖDA": { s: "Hon fick röda rosor på sin födelsedag.", st: "حصلت على ورود حمراء في عيد ميلادها." },
    "MATTAN": { s: "Katten ligger och sover på mattan.", st: "القطة نائمة على السجادة." },
    "MATTA": { s: "Vi köpte en ny matta till vardagsrummet.", st: "اشترينا سجادة جديدة لغرفة المعيشة." },
    "MANAT": { s: "Han har manat till lugn och ro.", st: "لقد دعا إلى الهدوء والسكينة." },
    "TANT": { s: "En snäll tant gav mig godis.", st: "سيدة لطيفة أعطتني الحلوى." },
    "SOFFAN": { s: "Vi sitter och myser i soffan.", st: "نجلس ونستمتع بالراحة على الأريكة." },
    "SOFFA": { s: "Detta är en mycket bekväm soffa.", st: "هذه أريكة مريحة جداً." },
    "FANS": { s: "Bandet har många hängivna fans.", st: "الفرقة لديها العديد من المعجبين المخلصين." },
    "GARDIN": { s: "Kan du dra för gardinen är du snäll?", st: "هل يمكنك إسدال الستارة من فضلك؟" },
    "DRAG": { s: "Han gjorde ett smart drag i schack.", st: "قام بحركة ذكية في الشطرنج." },
    "RING": { s: "Hon bär en vacker guldring på fingret.", st: "ترتدي خاتماً ذهبياً جميلاً في إصبعها." },
    "GRAD": { s: "Det är bara en grad varmt ute.", st: "درجة الحرارة درجة واحدة فقط في الخارج." },
    "GRAN": { s: "Vi klär en gran till jul.", st: "نزين شجرة التنوب لعيد الميلاد." },

    // Chapter 5: Health
    "TÅR": { s: "Tårarna rann nerför hennes kinder.", st: "انهمرت الدموع على خديها." },
    "RÅT": { s: "Man ska inte äta rått kött.", st: "لا ينبغي أكل اللحم الني." },
    "HALS": { s: "Jag har haft ont i halsen hela dagen.", st: "كان حلقي يؤلمني طوال اليوم." },
    "SAL": { s: "Patienten ligger på en stor sal.", st: "المريض يرقد في قاعة كبيرة." },
    "ÖGA": { s: "Håll ett öga på barnen.", st: "ابقِ عينك على الأطفال." },
    "PULS": { s: "Läkaren bad mig att känna pulsen.", st: "طلب مني الطبيب تحسس النبض." },
    "SLUP": { s: "Vi seglade med en gammal slup.", st: "أبحرنا بقارب قديم." },
    "PLUS": { s: "Det är ett stort plus i kanten.", st: "هذه ميزة إضافية كبيرة." },
    "FRISK": { s: "Det är skönt att andas frisk luft.", st: "من الرائع تنفس الهواء النقي." },
    "RISK": { s: "Det finns alltid en risk med affärer.", st: "هناك دائماً مخاطرة في الأعمال التجارية." },
    "SKRI": { s: "Ett gällt skri hördes i natten.", st: "سُمعت صرخة مدوية في الليل." },
    "LEVER": { s: "Levern renar blodet i kroppen.", st: "الكبد ينقي الدم في الجسم." },
    "ELEV": { s: "Han är en duktig elev i skolan.", st: "إنه تلميذ مجتهد في المدرسة." },
    "REV": { s: "Båten gick på ett undervattens rev.", st: "اصطدم القارب بشِعب مرجاني تحت الماء." },
    "SMÄRTA": { s: "Hon kände en stor smärta i ryggen.", st: "شعرت بألم كبير في ظهرها." },
    "SMÄRT": { s: "Han är lång och smärt i kroppen.", st: "هو طويل ونحيل الجسم." },
    "SÄRTA": { s: "En särta simmade i viken.", st: "سبحت بطة في الخليج." },
    "MÄTAR": { s: "Vi måste läsa av elmätaren nu.", st: "يجب أن نقرأ عداد الكهرباء الآن." },
    "ANDAS": { s: "Kom ihåg att andas in djupt.", st: "تذكر أن تتنفس بعمق." },
    "SAND": { s: "Stranden har vit och mjuk sand.", st: "الشاطئ به رمال بيضاء وناعمة." },
    "DANS": { s: "Får jag lov till en dans?", st: "هل تسمحين لي برقصة؟" },
    "ANDA": { s: "Vi arbetar i god anda tillsammans.", st: "نحن نعمل بروح طيبة معاً." },
    "STYRKA": { s: "Han visade prov på stor styrka.", st: "أظهر دليلاً على قوة كبيرة." },
    "YRKA": { s: "Åklagaren valde att yrka på fängelse.", st: "اختار المدعي العام المطالبة بالسجن." },
    "KRYA": { s: "Hoppas du kryar på dig snart.", st: "آمل أن تتعافى قريباً." },
    "TYSK": { s: "Jag träffade en trevlig tysk turist.", st: "التقيت بسائح ألماني لطيف." },
    "SJUKDOM": { s: "Han lider av en sällsynt sjukdom.", st: "هو يعاني من مرض نادر." },
    "SJUK": { s: "Jag är tyvärr sjuk idag.", st: "للأسف أنا مريض اليوم." },
    "DOM": { s: "Domaren avkunnade en hård dom.", st: "أصدر القاضي حكماً قاسياً." },
    "MJUK": { s: "Kudden är väldigt mjuk och skön.", st: "الوسادة ناعمة ومريحة جداً." },
    "MOS": { s: "Jag vill ha korv med mos.", st: "أريد سجقاً مع الهريس." },

    // Chapter 6: Work
    "LÖN": { s: "När får vi vår lön utbetald?", st: "متى سيتم دفع رواتبنا؟" },
    "ÖN": { s: "Vi åkte båt till en öde ö.", st: "ذهبنا بالقارب إلى جزيرة مهجورة." },
    "CHEF": { s: "Min chef är mycket förstående.", st: "مديري متفهم جداً." },
    "FE": { s: "Som en god fe i sagan.", st: "مثل جنية طيبة في الحكاية." },
    "YRKE": { s: "Vad har du för yrke?", st: "ما هي مهنتك؟" },
    "RYK": { s: "Ryk ihop och sluta bråka!", st: "تماسكوا وتوقفوا عن الشجار!" },
    "AVTAL": { s: "Vi har skrivit på ett nytt avtal.", st: "لقد وقعنا على اتفاقية جديدة." },
    "VALT": { s: "Han har valt att sluta arbeta.", st: "لقد اختار التوقف عن العمل." },
    "LAVA": { s: "Vulkanen sprutade ut het lava.", st: "قذف البركان حمماً ساخنة." },
    "PLIKT": { s: "Det är din plikt att hjälpa till.", st: "إنه واجبك أن تساعد." },
    "PILT": { s: "En liten pilt lekte på gården.", st: "صبي صغير كان يلعب في الفناء." },
    "LIKT": { s: "Det är likt honom att göra så.", st: "من عادته أن يفعل ذلك." },
    "BYGGA": { s: "Vi ska bygga ett nytt hus.", st: "سنبني منزلاً جديداً." },
    "BYGG": { s: "Detta är ett stabilt bygg.", st: "هذا بناء مستقر." },
    "GABY": { s: "Gaby är ett namn på en person.", st: "غابي هو اسم شخص." },
    "KONTOR": { s: "Jag arbetar på ett stort kontor.", st: "أعمل في مكتب كبير." },
    "KORT": { s: "Kan jag få betala med kort?", st: "هل يمكنني الدفع بالبطاقة؟" },
    "ORO": { s: "Jag känner en viss oro för framtiden.", st: "أشعر ببعض القلق تجاه المستقبل." },
    "ROT": { s: "Vi måste gå till botten med det onda.", st: "يجب أن نصل إلى جذر المشكلة." },
    "LOKAL": { s: "Vi hyrde en lokal för festen.", st: "استأجرنا مكاناً للحفلة." },
    "KOLA": { s: "Vill du ha en seg kola?", st: "هل تريد قطعة توفي لزجة؟" },
    "KALL": { s: "Vintern är mörk och kall.", st: "الشتاء مظلم وبارد." },
    "RIKARE": { s: "De rika blir allt rikare.", st: "الأغنياء يزدادون غنى." },
    "RIKA": { s: "De är rika på erfarenheter.", st: "هم أغنياء بالتجارب." },
    "KARR": { s: "Växten trivs i fuktiga karr.", st: "النبات ينمو في المستنقعات الرطبة." },
    "REKA": { s: "Vi måste reka området först.", st: "يجب أن نستطلع المنطقة أولاً." },
    "PENSION": { s: "Han gick i pension vid 65 års ålder.", st: "تقاعد في سن الخامسة والستين." },
    "SPION": { s: "Han anklagades för att vara spion.", st: "اتُهم بأنه جاسوس." },
    "PION": { s: "En vacker pion blommar i trädgården.", st: "زهرة فاوانيا جميلة تزهر في الحديقة." },
    "SNIP": { s: "En liten snip guppade på vågorna.", st: "قارب صغير كان يتمايل على الأمواج." },
    "SION": { s: "Sion är ett berg i Jerusalem.", st: "صهيون هو جبل في القدس." },

    // Chapter 7: Education
    "PROV": { s: "Vi har ett svårt prov imorgon.", st: "لدينا اختبار صعب غداً." },
    "ROV": { s: "Lejonet smög på sitt rov.", st: "تسلل الأسد نحو فريسته." },
    "KURS": { s: "Jag går en kurs i svenska.", st: "أنا أحضر دورة في اللغة السويدية." },
    "SUR": { s: "Varför är han så sur idag?", st: "لماذا هو غاضب جداً اليوم؟" },
    "RAST": { s: "Barnen leker ute på sin rast.", st: "الأطفال يلعبون في الخارج خلال استراحتهم." },
    "RAS": { s: "Det gick ett ras i bergen.", st: "حدث انهيار في الجبال." },
    "SKOLA": { s: "Skolan börjar klockan åtta.", st: "المدرسة تبدأ في الساعة الثامنة." },
    "SKAL": { s: "Äpplet har ett rött skal.", st: "التفاحة لها قشرة حمراء." },
    "TAVLA": { s: "Läraren skriver på en tavla.", st: "المعلم يكتب على السبورة." },
    "TALA": { s: "Tala är silver, tiga är guld.", st: "الكلام من فضة والسكوت من ذهب." },
    "KARTA": { s: "Vi behöver en karta för att hitta.", st: "نحتاج إلى خريطة لنجد الطريق." },
    "RAKA": { s: "Gå raka vägen hem.", st: "اذهب مباشرة إلى المنزل." },
    "ARTA": { s: "Det verkar arta sig väl.", st: "يبدو أن الأمور تتطور بشكل جيد." },
    "TERMIN": { s: "Höstterminen är ganska lång.", st: "فصل الخريف الدراسي طويل نوعاً ما." },
    "TIMER": { s: "Sätt en timer på tio minuter.", st: "اضبط المؤقت على عشر دقائق." },
    "RITEN": { s: "Riten utfördes med stort allvar.", st: "أقيمت الطقوس بجدية كبيرة." },
    "INTER": { s: "Inter vann matchen igår.", st: "فاز إنتر بالمباراة أمس." },
    "PENNOR": { s: "Jag har många färgglada pennor.", st: "لدي العديد من الأقلام الملونة." },
    "ROPEN": { s: "Ropen skallade över torget.", st: "دوت الصرخات في الساحة." },
    "REP": { s: "Klättra upp för ett rep.", st: "تسلق الحبل." },
    "REN": { s: "Luften är ren och klar här.", st: "الهواء نقي وصافٍ هنا." },
    "SKRIVA": { s: "Jag gillar att skriva brev.", st: "أحب كتابة الرسائل." },
    "SKIVA": { s: "Vill du ha en skiva bröd?", st: "هل تريد شريحة خبز؟" },
    "VIRKA": { s: "Min mormor lärde mig virka.", st: "جدتي علمتني الكروشيه." },
    "ARKIV": { s: "Dokumenten finns i vårt arkiv.", st: "الوثائق موجودة في أرشيفنا." },
    "STUDENT": { s: "Han är student vid universitetet.", st: "هو طالب في الجامعة." },
    "STUND": { s: "Vänta en liten stund är du snäll.", st: "انتظر لحظة من فضلك." },
    "DUNST": { s: "En dunst av parfym kändes.", st: "شوهدت سحابة من العطر." },
    "STUT": { s: "En ung stut betade på ängen.", st: "ثور صغير كان يرعى في المرج." },
    "SUNT": { s: "Det är sunt förnuft.", st: "إنه المنطق السليم." },

    // Chapter 8: Transport
    "VAGN": { s: "Hästen drog en tung vagn.", st: "سحب الحصان عربة ثقيلة." },
    "VAN": { s: "Han är van vid hårt arbete.", st: "هو معتاد على العمل الشاق." },
    "ÅRA": { s: "Vi tappade en åra i sjön.", st: "أسقطنا مجدافاً في البحيرة." },
    "RÅA": { s: "Grönsakerna är godast råa.", st: "الخضروات ألذ وهي نيئة." },
    "MOTOR": { s: "Bilen har en stark motor.", st: "السيارة لها محرك قوي." },
    "ROM": { s: "Alla vägar bär till Rom.", st: "كل الطرق تؤدي إلى روما." },
    "ORM": { s: "Jag är rädd för ormar.", st: "أنا أخاف من الثعابين." },
    "VÄGAR": { s: "Herrens vägar äro outgrundliga.", st: "طرق الرب لا يمكن سبر أغوارها." },
    "GRAV": { s: "Han vände sig i sin grav.", st: "تقلب في قبره (من الغضب)." },
    "VARG": { s: "Man ska inte ropa varg.", st: "لا ينبغي الصراخ بوجود ذئب (كذباً)." },
    "BILAR": { s: "Det finns många bilar på vägen.", st: "هناك العديد من السيارات على الطريق." },
    "BILA": { s: "Bödeln höjde sin bila.", st: "رفع الجلاد فأسه." },
    "LIRA": { s: "Ska vi lira lite boll?", st: "هل نلعب الكرة قليلاً؟" },
    "TRAFIK": { s: "Det är mycket trafik idag.", st: "حركة المرور كثيفة اليوم." },
    "KRAFT": { s: "Kunskap är makt och kraft.", st: "المعرفة هي سلطة وقوة." },
    "FRAKT": { s: "Vi betalar för frakt och emballage.", st: "نحن ندفع تكاليف الشحن والتغليف." },
    "FIKA": { s: "Ska vi ta en fika tillsammans?", st: "هل نأخذ استراحة قهوة معاً؟" },
    "BILIST": { s: "Varje bilist måste vara uppmärksam.", st: "يجب على كل سائق أن يكون منتبهاً." },
    "LIST": { s: "Han använde list för att vinna.", st: "استخدم المكر ليفوز." },
    "SLIT": { s: "Det var mycket slit och släp.", st: "كان هناك الكثير من الكدح والعناء." },
    "VAGNAR": { s: "Tåget har många vagnar.", st: "القطار له العديد من العربات." },
    "VANA": { s: "Gammal vana sitter i.", st: "العادات القديمة تموت بصعوبة." },
    "STATION": { s: "Vi möts vid nästa station.", st: "نلتقي في المحطة التالية." },
    "STAT": { s: "Staten ska tjäna folket.", st: "يجب أن تخدم الدولة الشعب." },
    "STAN": { s: "Vi ska åka in till stan.", st: "سنذهب إلى المدينة." },
    "NOTA": { s: "Kan vi få in notan, tack?", st: "هل يمكننا الحصول على الفاتورة، من فضلك؟" },
    "TONA": { s: "Färgerna började tona bort.", st: "بدأت الألوان تتلاشى." },

    // Chapter 9: Law
    "LAG": { s: "Lagen är lika för alla.", st: "القانون سواسية للجميع." },
    "GAL": { s: "Tuppen gal tidigt på morgonen.", st: "يصيح الديك في الصباح الباكر." },
    "MOD": { s: "Det krävs mod för att tala sanning.", st: "يتطلب الأمر شجاعة لقول الحقيقة." },
    "RÄTT": { s: "Gör det som är rätt.", st: "افعل ما هو صواب." },
    "TÄT": { s: "Skogen var mörk och tät.", st: "كانت الغابة مظلمة وكثيفة." },
    "BROTT": { s: "Brott lönar sig inte.", st: "الجريمة لا تفيد." },
    "BORT": { s: "Gå bort och kom aldrig tillbaka.", st: "اذهب بعيداً ولا تعد أبداً." },
    "BOTT": { s: "Jag har bott här i hela mitt liv.", st: "لقد عشت هنا طوال حياتي." },
    "POLIS": { s: "Ring polisen om du ser något.", st: "اتصل بالشرطة إذا رأيت شيئاً." },
    "SILO": { s: "Bonden lagrar säd i en silo.", st: "يخزن المزارع الحبوب في صومعة." },
    "LAGAR": { s: "Vi måste följa landets lagar.", st: "يجب أن نتبع قوانين البلاد." },
    "LAGA": { s: "Jag ska laga mat ikväll.", st: "سأطبخ العشاء الليلة." },
    "GALA": { s: "De gick på en fin gala.", st: "ذهبوا إلى حفل راقٍ." },
    "DOMARE": { s: "Domaren blåste av matchen.", st: "أطلق الحكم صافرة نهاية المباراة." },
    "DOMAR": { s: "Guds domar är rättvisa.", st: "أحكام الله عادلة." },
    "DAMER": { s: "Mina damer och herrar.", st: "سيداتي وسادتي." },
    "MODE": { s: "Hon följer alltid senaste mode.", st: "هي تتبع دائماً أحدث صيحات الموضة." },
    "REGLER": { s: "Det finns regler man måste följa.", st: "هناك قواعد يجب اتباعها." },
    "REGEL": { s: "Ingen regel utan undantag.", st: "لا توجد قاعدة بدون استثناء." },
    "LEGER": { s: "Brons är en legering av koppar.", st: "البرونز هو سبيكة من النحاس." },
    "GER": { s: "Den som ger, han får.", st: "من يعطي، يأخذ." },
    "STRAFF": { s: "Han fick ett strängt straff.", st: "تلقى عقاباً شديداً." },
    "STAFF": { s: "Hela vår staff är här.", st: "طاقمنا بأكمله هنا." },
    "FART": { s: "Det var full fart hela dagen.", st: "كانت السرعة قصوى طوال اليوم." },
    "SAFT": { s: "Barnen dricker saft och äter bullar.", st: "الأطفال يشربون العصير ويأكلون الكعك." },
    "ARVET": { s: "Arvet fördelades mellan barnen.", st: "تم توزيع الإرث بين الأبناء." },
    "ARV": { s: "Miljön är ett arv till våra barn.", st: "البيئة إرث لأطفالنا." },
    "VAR": { s: "Var har du varit någonstans?", st: "أين كنت؟" },
    "RET": { s: "Han gjorde det bara på ret.", st: "فعل ذلك فقط للإغاظة." },

    // Chapter 10: Islam
    "TRO": { s: "Min tro ger mig styrka.", st: "إيماني يمنحني القوة." },
    "ROT": { s: "Kärleken är roten till allt gott.", st: "الحب هو جذر كل خير." },
    "FRID": { s: "Vila i frid.", st: "ارقد في سلام." },
    "FRI": { s: "Tanken är fri.", st: "الفكر حر." },
    "FRED": { s: "Vi vill ha fred på jorden.", st: "نريد السلام على الأرض." },
    "RED": { s: "Han red på en vit häst.", st: "ركب حصاناً أبيض." },
    "ALLAH": { s: "Det finns ingen gud utom Allah.", st: "لا إله إلا الله." },
    "HALL": { s: "Vi möttes i en stor hall.", st: "التقينا في قاعة كبيرة." },
    "ALLA": { s: "Alla människor är födda fria.", st: "يولد جميع الناس أحراراً." },
    "ISLAM": { s: "Islam betyder underkastelse och fred.", st: "الإسلام يعني الاستسلام والسلام." },
    "SILA": { s: "Sila snacket och kom till saken.", st: "صفِّ الكلام وادخل في صلب الموضوع." },
    "MILA": { s: "De vandrade en hel mila.", st: "ساروا ميلاً كاملاً." },
    "ZAKAT": { s: "Zakat är en av islams pelare.", st: "الزكاة هي أحد أركان الإسلام." },
    "KATA": { s: "Han tränar kata varje dag.", st: "يتدرب على الكاتا كل يوم." },
    "AKTA": { s: "Akta dig för hunden!", st: "احذر من الكلب!" },
    "MOSKÉN": { s: "Vi går till moskén på fredagar.", st: "نذهب إلى المسجد أيام الجمعة." },
    "MOSKÉ": { s: "Det finns en vacker moské här.", st: "يوجد مسجد جميل هنا." },
    "SON": { s: "Han är sin fars son.", st: "إنه ابن أبيه." },
    "SKO": { s: "Klämmer skon någonstans?", st: "هل يضغط الحذاء في مكان ما؟ (هل هناك مشكلة؟)" },
    "KORNA": { s: "Korna betar lugnt på ängen.", st: "الأبقار ترعى بهدوء في المرج." },
    "KORA": { s: "Vi ska kora en vinnare ikväll.", st: "سنختار فائزاً الليلة." },
    "ARK": { s: "Noaks ark räddade djuren.", st: "سفينة نوح أنقذت الحيوانات." },
    "KAN": { s: "Kan du hjälpa mig med detta?", st: "هل يمكنك مساعدتي في هذا؟" },
    "HELIGT": { s: "Detta är ett heligt rum.", st: "هذه غرفة مقدسة." },
    "HELIG": { s: "Koranen är en helig bok.", st: "القرآن كتاب مقدس." },
    "HELT": { s: "Jag håller med dig helt och hållet.", st: "أنا أتفق معك تماماً." },
    "LITE": { s: "Kan jag få lite mer kaffe?", st: "هل يمكنني الحصول على المزيد من القهوة؟" },
    "PROFET": { s: "Muhammed är Guds sista profet.", st: "محمد هو خاتم أنبياء الله." },
    "POET": { s: "Han var en känd poet.", st: "كان شاعراً مشهوراً." },
    "PORT": { s: "Han stod vid himmelens port.", st: "وقف عند بوابة السماء." },
    "FORT": { s: "Tiden går så fort när man har roligt.", st: "الوقت يمضي بسرعة عندما تستمتع." },
    "REP": { s: "Ett rep är starkare än en tråd.", st: "الحبل أقوى من الخيط." }
};

// Apply enhancements
let updatedCount = 0;
for (const [word, newData] of Object.entries(enhancements)) {
    // Regex to find the data object for the specific word
    // Pattern looks for: "WORD": { t: "...", s: "...", st: "..." }
    // We need to be careful to match the specific word key
    const regex = new RegExp(`"${word}": \\{ t: "([^"]+)", s: "([^"]+)", st: "([^"]+)" \\}`, 'g');

    if (regex.test(content)) {
        content = content.replace(regex, `"${word}": { t: "$1", s: "${newData.s}", st: "${newData.st}" }`);
        updatedCount++;
    } else {
        console.warn(`Could not find entry for ${word}`);
    }
}

fs.writeFileSync(generatorPath, content);
console.log(`Updated ${updatedCount} sentences in generate_advanced_levels.js`);
