const fs = require('fs');

// Read data.js
let dataContent = fs.readFileSync('./data.js', 'utf-8');

// Parse
let dictionaryData;
let prefix = "";
let suffix = "";

if (dataContent.includes('const dictionaryData =')) {
    prefix = "const dictionaryData = ";
    suffix = ";";
    dictionaryData = JSON.parse(dataContent.replace(prefix, '').replace(/;$/, ''));
} else {
    process.exit(1);
}

const COL_SWE = 2;
const COL_EX = 6;
const COL_EX_ARB = 7;

const updates = {
    "Långtgående": { swe: "Beslutet fick långtgående konsekvenser.", arb: "كان للقرار عواقب بعيدة المدى." },
    "Långväga": { swe: "Vi fick långväga gäster från Australien.", arb: "استقبلنا ضيوفاً قادمين من مكان بعيد (أستراليا)." },
    "Löjeväckande": { swe: "Hennes påstående var helt löjeväckande.", arb: "كان ادعاؤها مثيراً للسخرية تماماً." },
    "Lönande": { swe: "Det är lönande att investera i utbildning.", arb: "الاستثمار في التعليم أمر مجدٍ (مربح)." },
    "Lönt": { swe: "Det är inte lönt att bråka om småsaker.", arb: "لا جدوى من الشجار حول التوافه." },
    "Matt": { swe: "Färgerna på tavlan var matta och bleka.", arb: "كانت ألوان اللوحة باهتة وغير لامعة." },
    "Medelålders": { swe: "En medelålders man satt på bänken.", arb: "كان رجل في منتصف العمر يجلس على المقعد." },
    "Medryckande": { swe: "Musiken var så medryckande att alla dansade.", arb: "كانت الموسيقى حماسية جداً لدرجة أن الجميع رقص." },
    "Mellersta": { swe: "Vi bor på den mellersta våningen.", arb: "نحن نسكن في الطابق الأوسط." },
    "Menande": { swe: "Han gav mig en menande blick.", arb: "أعطاني نظرة ذات مغزى." },
    "Mindre": { swe: "Jag vill ha en mindre portion tack.", arb: "أريد حصة أصغر من فضلك." },
    "Missvisande": { swe: "Statistiken kan vara missvisande om den tolkas fel.", arb: "يمكن أن تكون الإحصائيات مضللة إذا فُسرت بشكل خاطئ." },
    "Motbjudande": { swe: "Maten luktade motbjudande.", arb: "كانت رائحة الطعام مقززة (منفرة)." },
    "Motsvarande": { swe: "Du måste ha motsvarande utbildning för jobbet.", arb: "يجب أن يكون لديك تعليم مماثل (معادل) للوظيفة." },
    "Motsägande": { swe: "Vittnenas uppgifter var motsägande.", arb: "كانت إفادات الشهود متناقضة." },
    "Målande": { swe: "Han gav en målande beskrivning av händelsen.", arb: "قدم وصفاً تصويرياً (حياً) للحدث." },
    "Mördande": { swe: "Konkurrensen på marknaden är mördande.", arb: "المنافسة في السوق شرسة (قاتلة)." },
    "Nedgörande": { swe: "Filmen fick nedgörande kritik.", arb: "تلقى الفيلم نقداً لاذعاً (مدمراً)." },
    "Nedlåtande": { swe: "Hon talade till honom i en nedlåtande ton.", arb: "تحدثت إليه بنبرة متعالية." },
    "Nedre": { swe: "Smärtan satt i den nedre delen av ryggen.", arb: "كان الألم في الجزء السفلي من الظهر." },
    "Nedslående": { swe: "Resultatet av provet var nedslående.", arb: "كانت نتيجة الاختبار مخيبة للآمال." },
    "Nedsättande": { swe: "Man ska inte använda nedsättande ord om andra.", arb: "لا ينبغي استخدام كلمات مهينة (تحقيرية) عن الآخرين." },
    "Nere": { swe: "Han verkar lite nere idag.", arb: "يبدو محبطاً (مكتئباً) بعض الشيء اليوم." },
    "Nervkittlande": { swe: "Det var en nervkittlande finalmatch.", arb: "كانت مباراة نهائية مثيرة للأعصاب." },
    "Noga": { swe: "Var noga med att låsa dörren.", arb: "كن حريصاً (دقيقاً) على قفل الباب." },
    "Nutida": { swe: "Nutida konst kan vara svår att förstå.", arb: "الفن المعاصر قد يكون صعب الفهم." },
    "Nuvarande": { swe: "Min nuvarande adress är Storgatan 1.", arb: "عنواني الحالي هو شارع Storgatan 1." },
    "Näck": { swe: "Han badade näck i sjön.", arb: "سبح عارياً في البحيرة." },
    "Närande": { swe: "Soppan var varm och närande.", arb: "كان الحساء دافئاً ومغذياً." },
    "Närmare": { swe: "Kom lite närmare så jag ser dig.", arb: "اقترب قليلاً حتى أراك." },
    "Närstående": { swe: "Bara de närmast närstående var inbjudna.", arb: "تمت دعوة الأقارب المقربين فقط." },
    "Närvarande": { swe: "Läkaren var närvarande under operationen.", arb: "كان الطبيب حاضراً أثناء العملية." },
    "Nästa": { swe: "Vi ses nästa vecka!", arb: "أراك في الأسبوع القادم!" },
    "Oberoende": { swe: "Domstolen ska vara oberoende och opartisk.", arb: "يجب أن تكون المحكمة مستقلة ومحايدة." },
    "Oense": { swe: "Vi är oense om vilken väg vi ska ta.", arb: "نحن مختلفون حول الطريق الذي يجب أن نسلكه." },
    "Oförrättat": { swe: "Han fick återvända med oförrättat ärende.", arb: "اضطر للعودة دون إنجاز مهمته." },
    "Oförstående": { swe: "Hon såg helt oförstående ut.", arb: "بدت غير فاهمة للأمر تماماً." },
    "Oherrans": { swe: "De förde ett oherrans liv på festen.", arb: "أحدثوا ضجيجاً فظيعاً في الحفلة." },
    "Olaga": { swe: "Han greps för olaga intrång.", arb: "قُبض عليه بتهمة التعدي غير القانوني." },
    "Oliktänkande": { swe: "Regimen fängslade många oliktänkande.", arb: "سجن النظام العديد من المعارضين (مخالفي الرأي)." },
    "Olycksbådande": { swe: "Det hördes ett olycksbådande muller.", arb: "سُمع هدير ينذر بالسوء." },
    "Omaka": { swe: "De var ett omaka par.", arb: "كانا زوجين غير متوافقين." },
    "Omfattande": { swe: "Polisen gjorde en omfattande utredning.", arb: "أجرت الشرطة تحقيقاً شاملاً." },
    "Ont": { swe: "Jag har ont i huvudet.", arb: "لدي صداع (ألم في الرأس)." },
    "Opassande": { swe: "Han drog ett opassande skämt vid middagen.", arb: "ألقى نكتة غير لائقة أثناء العشاء." },
    "Orange": { swe: "Himlen färgades orange vid solnedgången.", arb: "تلونت السماء بالبرتقالي عند الغروب." },
    "Ordinarie": { swe: "Vi har ordinarie öppettider idag.", arb: "لدينا ساعات عمل عادية اليوم." },
    "Osammanhängande": { swe: "Hans berättelse var rörig och osammanhängande.", arb: "كانت قصته فوضوية وغير مترابطة." },
    "Osams": { swe: "Barnen blev osams om leksaken.", arb: "تشاجر الأطفال حول اللعبة." },
    "Otalt": { swe: "Vi har en del otalt med varandra.", arb: "بيننا حساب لم يُصفَّ (أمور عالقة)." },
    "Otillfredsställande": { swe: "Svaret var helt otillfredsställande.", arb: "كانت الإجابة غير مرضية تماماً." },
    "Outstanding": { swe: "Hennes insats var helt outstanding.", arb: "كان أداؤها متميزاً (خارقاً) للعادة." },
    "Ovanstående": { swe: "Se ovanstående text för instruktioner.", arb: "انظر النص أعلاه للتعليمات." },
    "Ovetande": { swe: "Hon var helt ovetande om planen.", arb: "كانت جاهلة تماماً بالخطة." },
    "Ovidkommande": { swe: "Dina åsikter är ovidkommande i den här frågan.", arb: "آراؤك غير ذات صلة (لا علاقة لها) في هذه المسألة." },
    "Oäkta": { swe: "Det visade sig vara en oäkta diamant.", arb: "تبين أنها ألماسة مزيفة (غير حقيقية)." },
    "Passé": { swe: "Den modeflugan är helt passé nu.", arb: "تلك الموضة قد عفى عليها الزمن تماماً الآن." },
    "Poppis": { swe: "Bandet är väldigt poppis bland ungdomar.", arb: "الفرقة محبوبة جداً (شائعة) بين الشباب." },
    "Prejudicerande": { swe: "Domen kan bli prejudicerande för liknande fall.", arb: "قد يشكل الحكم سابقة قضائية لقضايا مماثلة." },
    "Pressande": { swe: "Han var i en mycket pressande situation.", arb: "كان في وضع ضاغط للغاية." },
    "Prima": { swe: "Detta är prima virke.", arb: "هذا خشب من الدرجة الأولى (ممتاز)." },
    "Privatpraktiserande": { swe: "Han är privatpraktiserande läkare.", arb: "إنه طبيب يمارس المهنة بشكل خاص." },
    "Prostituerad": { swe: "Filmen handlade om en prostituerad kvinna.", arb: "كان الفيلم يدور حول امرأة تعمل في الدعارة." },
    "Prövande": { swe: "Hon kastade en prövande blick på honom.", arb: "ألقت عليه نظرة فاحصة (مختبرة)." },
    "Publikfriande": { swe: "Han gjorde en publikfriande gest.", arb: "قام بإيماءة لاسترضاء الجمهور." },
    "Påfrestande": { swe: "Resan var lång och påfrestande.", arb: "كانت الرحلة طويلة ومرهقة." },
    "Påträngande": { swe: "Försäljaren var väldigt påträngande.", arb: "كان البائع لحوحاً (تطفلياً) للغاية." },
    "Påökt": { swe: "Jag hoppas få påökt i lön i år.", arb: "آمل الحصول على زيادة في الراتب هذا العام." },
    "Rafflande": { swe: "Matchen fick en rafflande avslutning.", arb: "كانت للمباراة نهاية مثيرة." },
    "Rama": { swe: "Det var rena rama turen att vi hann.", arb: "كان محض حظ أننا لحقنا." },
    "Rasande": { swe: "Chefen var rasande över misstaget.", arb: "كان المدير غاضباً جداً بسبب الخطأ." },
    "Reda": { swe: "Vi fick pengar i reda pangar.", arb: "حصلنا على المال نقداً." }, // Idiom "reda pengar"
    "Redo": { swe: "Är du redo att åka nu?", arb: "هل أنت مستعد للذهاب الآن؟" },
    "Reko": { swe: "Han verkar vara en reko kille.", arb: "يبدو أنه شاب طيب (شريف)." },
    "Respektive": { swe: "De gick till sina respektive rum.", arb: "ذهبوا إلى غرفهم الخاصة بهم." },
    "Rikstäckande": { swe: "Vi har ett rikstäckande nätverk av butiker.", arb: "لدينا شبكة متاجر تغطي جميع أنحاء البلاد." },
    "Ringa": { swe: "Det är av ringa betydelse.", arb: "هذا ذو أهمية ضئيلة." },
    "Rosa": { swe: "Hon målade väggarna rosa.", arb: "طلت الجدران باللون الوردي." },
    "Rosenrasande": { swe: "Han blev rosenrasande när han hörde det.", arb: "استشاط غضباً عندما سمع ذلك." },
    "Rungande": { swe: "Han fick en rungande applåd.", arb: "تلقى تصفيقاً مدوياً." },
    "Rådande": { swe: "Under rådande omständigheter kan vi inte ses.", arb: "في ظل الظروف الراهنة لا يمكننا اللقاء." },
    "Rådgivande": { swe: "Kommittén har endast en rådgivande funktion.", arb: "للجنة وظيفة استشارية فقط." },
    "Rättskaffens": { swe: "Han är en rättskaffens människa.", arb: "إنه إنسان مستقيم (شريف)." },
    "Rörande": { swe: "Det var ett rörande ögonblick.", arb: "كانت لحظة مؤثرة." },
    "Sabla": { swe: "Vilken sabla oordning!", arb: "يا لها من فوضى ملعونة!" },
    "Sammanboende": { swe: "Lagen gäller för sammanboende par.", arb: "ينطبق القانون على الأزواج المتعايشين." },
    "Sams": { swe: "Nu är vi sams igen.", arb: "نحن متصالحون الآن من جديد." },
    "Samtida": { swe: "Mozart och Haydn var samtida.", arb: "كان موزارت وهايدن معاصرين لبعضهما." },
    "Samtliga": { swe: "Samtliga passagerare överlevde olyckan.", arb: "نجا جميع الركاب من الحادث." },
    "Schackmatt": { swe: "Han satte motståndaren schackmatt.", arb: "وضع خصمه في وضع كش ملك (هزمه)." },
    "Sedelärande": { swe: "Det var en sedelärande historia.", arb: "كانت قصة ذات عبرة أخلاقية." },
    "Sekunda": { swe: "Detta är varor av sekunda kvalitet.", arb: "هذه بضائع من الدرجة الثانية (جودة أقل)." },
    "Sentida": { swe: "Det är en sentida tolkning av verket.", arb: "إنه تفسير حديث للعمل الفني." },
    "Självförsörjande": { swe: "Landet är självförsörjande på livsmedel.", arb: "البلاد مكتفية ذاتياً في الغذاء." },
    "Se": { swe: "Se upp för hunden!", arb: "احترس من الكلب!" }, // Generic Se fix if caught
    "Självuppfyllande": { swe: "Det blev en självuppfyllande profetia.", arb: "أصبحت نبوءة تحقق ذاتها." },
    "Skakande": { swe: "Vi fick ett skakande besked.", arb: "تلقينا خبراً مروّعاً." },
    "Skakis": { swe: "Jag var helt skakis efter krocken.", arb: "كنت مرتعداً تماماً بعد الاصطدام." },
    "Skoj": { swe: "Det ska bli skoj att träffas.", arb: "سيكون من الممتع أن نلتقي." },
    "Skrattretande": { swe: "Förslaget var helt skrattretande.", arb: "كان الاقتراح مثيراً للضحك تماماً." },
    "Skriande": { swe: "Det råder en skriande brist på bostäder.", arb: "هناك نقص صارخ في السكن." },
    "Skrymmande": { swe: "Paketet var stort och skrymmande.", arb: "كان الطرد كبيراً وضخماً." },
    "Skräckinjagande": { swe: "Monstret såg skräckinjagande ut.", arb: "بدا الوحش مرعباً." },
    "Skrämmande": { swe: "Utvecklingen är skrämmande.", arb: "التطور مخيف." },
    "Skärande": { swe: "Det hördes ett skärande ljud från motorn.", arb: "سُمع صوت حاد (صرير) من المحرك." },
    "Slut": { swe: "Mjölken är slut.", arb: "الحليب نفد." },
    "Slående": { swe: "Likheten mellan dem är slående.", arb: "الشبه بينهما لافت للنظر." },
    "Small": { swe: "Jag behöver en tröja i storlek small.", arb: "أحتاج إلى قميص بمقاس صغير." },
    "Smaskens": { swe: "Tårtan var smaskens!", arb: "الكعكة كانت لذيذة جداً!" },
    "Smäktande": { swe: "Sångaren sjöng en smäktande ballad.", arb: "غنى المغني أغنية عاطفية (شجية)." },
    "Smärre": { swe: "Bilen fick endast smärre skador.", arb: "لحقت بالسيارة أضرار طفيفة فقط." },
    "Smärtstillande": { swe: "Han tog en smärtstillande tablett.", arb: "تناول قرصاً مسكناً للألم." },
    "Somliga": { swe: "Somliga tycker om kaffe, andra inte.", arb: "البعض يحب القهوة، والبعض الآخر لا." },
    "Spännande": { swe: "Det var en mycket spännande match.", arb: "كانت مباراة مثيرة للغاية." },
    "Stackars": { swe: "Stackars liten som har gjort sig illa.", arb: "يا للمسكين الصغير الذي آذى نفسه." },
    "Stadigvarande": { swe: "Han söker ett stadigvarande arbete.", arb: "يبحث عن عمل دائم (مستقر)." },
    "Stilbildande": { swe: "Arkitekten var stilbildande för sin tid.", arb: "كان المهندس المعماري رائد أسلوب في عصره." },
    "Stilla": { swe: "Havet låg alldeles stilla.", arb: "كان البحر هادئاً تماماً." },
    "Strykande": { swe: "Varorna hade en strykande åtgång.", arb: "نفدت البضائع بسرعة هائلة (رواج كبير)." },
    "Strålande": { swe: "Vädret var strålande vackert.", arb: "كان الطقس جميلاً ومشرقاً." },
    "Stående": { swe: "Vi fick stående ovationer.", arb: "حصلنا على تصفيق حار (وقوفاً)." },
    "Ställföreträdande": { swe: "Den ställföreträdande chefen ledde mötet.", arb: "قاد نائب المدير (القائم بالأعمال) الاجتماع." },
    "Svepande": { swe: "Hon gjorde en svepande gest med handen.", arb: "قامت بإيماءة كاسحة بيدها." },
    "Svindlande": { swe: "Priset var svindlande högt.", arb: "كان السعر مرتفعاً بشكل مذهل." },
    "Södra": { swe: "Vi bor i södra Sverige.", arb: "نسكن في جنوب السويد." },
    "Talande": { swe: "Hans tystnad var talande.", arb: "كان صمته معبراً (ناطقاً)." },
    "Tankeväckande": { swe: "Filmen var djupt tankeväckande.", arb: "كان الفيلم مثيراً للتفكير بعمق." },
    "Tidsödande": { swe: "Det är ett tidsödande arbete att sortera papper.", arb: "فرز الأوراق عمل يستهلك الكثير من الوقت." },
    "Tilldragande": { swe: "Hon har ett mycket tilldragande utseende.", arb: "لديها مظهر جذاب للغاية." },
    "Tillfredsställande": { swe: "Resultatet var tillfredsställande för alla parter.", arb: "كانت النتيجة مرضية لجميع الأطراف." },
    "Tillkommande": { swe: "Inga tillkommande kostnader tillkommer.", arb: "لا توجد تكاليف إضافية." },
    "Tillmötesgående": { swe: "Personalen var mycket tillmötesgående och hjälpsam.", arb: "كان الموظفون متعاونين وخدومين جداً." },
    "Tongivande": { swe: "Han är en tongivande politiker i regionen.", arb: "إنه سياسي مؤثر (قائد للرأي) في المنطقة." },
    "Troende": { swe: "Hon är djupt troende.", arb: "إنها مؤمنة بعمق." },
    "Tryckande": { swe: "Värmen var tryckande.", arb: "كانت الحرارة خانقة." },
    "Träffande": { swe: "Han gav en träffande beskrivning av problemet.", arb: "قدم وصفاً دقيقاً (صائباً) للمشكلة." },
    "Trängande": { swe: "Jag har ett trängande behov av semester.", arb: "لدي حاجة ملحة لإجازة." },
    "Tårdrypande": { swe: "Det var ett tårdrypande avsked.", arb: "كان وداعاً مبكياً." },
    "Udda": { swe: "Han har lite udda vanor.", arb: "لديه عادات غريبة بعض الشيء." },
    "Undergörande": { swe: "Salvan hade en undergörande effekt på såret.", arb: "كان للمرهم مفعول عجيب (معجزة) على الجرح." },
    "Underhållande": { swe: "Showen var mycket underhållande.", arb: "كان العرض مسلياً للغاية." },
    "Underliggande": { swe: "Vi måste hitta den underliggande orsaken till felet.", arb: "يجب أن نجد السبب الكامن وراء الخطأ." },
    "Understa": { swe: "Boken ligger i den understa lådan.", arb: "الكتاب موجود في الدرج السفلي." },
    "Undfallande": { swe: "Han var alltför undfallande mot chefen.", arb: "كان مذعناً (مطاوعاً) جداً للمدير." },
    "Undre": { swe: "De bor på undre botten.", arb: "يسكنون في الطابق الأرضي السفلي." },
    "Uppfriskande": { swe: "Ett dopp i sjön var uppfriskande.", arb: "كانت الغطسة في البحيرة منعشة." },
    "Uppiggande": { swe: "Kaffe har en uppiggande effekt.", arb: "للقوة تأثير منشط." },
    "Upplyftande": { swe: "Det var en upplyftande predikan.", arb: "كانت موعظة ترفع المعنويات." },
    "Upprörande": { swe: "Det är upprörande hur de behandlar djur.", arb: "إنه لأمر مشين كيف يعاملون الحيوانات." },
    "Uppseendeväckande": { swe: "Hennes klädsel var uppseendeväckande.", arb: "كان ملبسها ملفتاً للأنظار." },
    "Uppskakande": { swe: "Det var en uppskakande upplevelse.", arb: "كانت تجربة مروعة (هزت المشاعر)." },
    "Uppslitande": { swe: "Skilsmässan var uppslitande för hela familjen.", arb: "كان الطلاق ممزقاً للعائلة بأكملها." },
    "Urminnes": { swe: "Seden har funnits sedan urminnes tider.", arb: "العادة موجودة منذ الأزل (أوقات سحيقة)." },
    "Utmanande": { swe: "Hon hade en utmanande klänning på sig.", arb: "كانت ترتدي فستاناً جريئاً (مثيراً)." },
    "Utomstående": { swe: "Detta är svårt att förstå för en utomstående.", arb: "هذا صعب الفهم على شخص خارجي." },
    "Utslagsgivande": { swe: "Rösten blev utslagsgivande i valet.", arb: "كان الصوت حاسماً في الانتخابات." },
    "Uttömmande": { swe: "Vi fick ett uttömmande svar på frågan.", arb: "حصلنا على إجابة وافية (شاملة) على السؤال." },
    "Utvärtes": { swe: "Endast för utvärtes bruk.", arb: "للاستخدام الخارجي فقط." },
    "Vanebildande": { swe: "Medicinen kan vara vanebildande.", arb: "الدواء قد يسبب الإدمان (التعود)." },
    "Varse": { swe: "Jag blev plötsligt varse att någon stod bakom mig.", arb: "أدركت فجأة أن شخصاً ما يقف خلفي." },
    "Vederbörande": { swe: "Du bör kontakta vederbörande chef.", arb: "يجب عليك الاتصال بالمدير المعني." },
    "Vidare": { swe: "Vi har inga vidare planer för kvällen.", arb: "ليس لدينا أي خطط أخرى للمساء." },
    "Vilse": { swe: "Vi gick vilse i skogen.", arb: "ضللنا الطريق في الغابة." },
    "Vilseledande": { swe: "Informationen var vilseledande.", arb: "كانت المعلومات مضللة." },
    "Vindstilla": { swe: "Det var helt vindstilla på sjön.", arb: "كان الجو ساكناً بلا رياح تماماً في البحيرة." },
    "Vinnande": { swe: "Hon har ett vinnande sätt.", arb: "لديها أسلوب جذاب (رائع)." },
    "Välgörande": { swe: "Massage är välgörande för stela muskler.", arb: "التدليك مفيد للعضلات المتيبسة." },
    "Västra": { swe: "Solen går ner i västra delen av himlen.", arb: "تغرب الشمس في الجزء الغربي من السماء." },
    "Yttermera": { swe: "Till yttermera visso skrev han under.", arb: "ولمزيد من التأكيد قام بالتوقيع." },
    "Yttersta": { swe: "Vi gör vårt yttersta för att hjälpa till.", arb: "نبذل قصارى جهدنا للمساعدة." },
    "Yttre": { swe: "Vi bedömer inte efter det yttre.", arb: "نحن لا نحكم على المظهر الخارجي." },
    "Äkta": { swe: "Det är en äkta pärla.", arb: "إنها لؤلؤة حقيقية." },
    "Öde": { swe: "Huset låg öde och tomt.", arb: "كان المنزل مهجوراً وخالياً." },
    "Öronbedövande": { swe: "Musiken spelades på öronbedövande volym.", arb: "عُزفت الموسيقى بصوت يصم الآذان." },
    "Östra": { swe: "Vinden kommer från östra hållet.", arb: "الرياح قادمة من الجهة الشرقية." },
    "Övergripande": { swe: "Vi har ett övergripande ansvar för projektet.", arb: "لدينا مسؤولية شاملة عن المشروع." },
    "Övergående": { swe: "Smärtan är bara övergående.", arb: "الألم مجرد عارض (مؤقت)." },
    "Överhängande": { swe: "Det finns en överhängande risk för ras.", arb: "هناك خطر وشيك للانهيار." },
    "Överraskande": { swe: "Besöket var helt överraskande.", arb: "كانت الزيارة مفاجئة تماماً." },
    "Översta": { swe: "Boken står på översta hyllan.", arb: "الكتاب موجود على الرف العلوي." },
    "Översvallande": { swe: "Hon hälsade med översvallande värme.", arb: "رحبت بحرارة فياضة." },
    "Övertygande": { swe: "Han lät mycket övertygande.", arb: "بدا مقنعاً جداً." },
    "Överväldigande": { swe: "Gensvaret var överväldigande.", arb: "كانت الاستجابة هائلة (ساحقة)." },
    "Övre": { swe: "Han hade ont i övre delen av magen.", arb: "كان لديه ألم في الجزء العلوي من البطن." }
};

let modifiedCount = 0;

dictionaryData.forEach(entry => {
    const word = entry[COL_SWE] ? entry[COL_SWE].trim() : "";
    if (updates[word]) {
        console.log(`Fixing [${word}]...`);
        entry[COL_EX] = updates[word].swe;
        entry[COL_EX_ARB] = updates[word].arb;
        modifiedCount++;
    }
});

const newContent = prefix + JSON.stringify(dictionaryData, null, 2) + suffix;
fs.writeFileSync('./data.js', newContent, 'utf-8');

console.log(`\n✅ Fixed ${modifiedCount} Adjective Tautologies (Batch 3).`);
