// Manual replacements for words with long or missing sentences
// Format: WORD: { s: "Swedish Sentence", t: "Arabic Translation" }

const MANUAL_SENTENCES = {
    "HAV": { s: "Fiskar simmar i havet.", t: "تسبح الأسماك في البحر." },
    "GOLV": { s: "Mattan ligger på golvet.", t: "السجادة ممدودة على الأرضية." },
    "LOKAL": { s: "Vi hyr en lokal till festen.", t: "نستأجر مكاناً للحفلة." },
    "VINKEL": { s: "Solen skiner i en annan vinkel.", t: "تسطع الشمس بزاوية أخرى." },
    "IGEN": { s: "Kom gärna tillbaka igen!", t: "أهلاً بك مجدداً!" },
    "BAKLÄXA": { s: "Han fick bakläxa på provet.", t: "رسب في الاختبار وعليه إعادته." },
    "AGG": { s: "Han hyser agg mot mig.", t: "إنه يحمل ضغينة ضدي." },
    "RAGG": { s: "Hunden ryste ragg.", t: "انتصب شعر الكلب." },
    "VID": { s: "Huset ligger vid sjön.", t: "يقع المنزل عند البحيرة." },
    "BITSK": { s: "Hunden var bitsk och arg.", t: "كان الكلب شرساً وغاضباً." },
    "DÄRFÖR": { s: "Jag är sjuk, därför stannar jag.", t: "أنا مريض، لذلك سأبقى." },
    "SLUTEN": { s: "Sällskapet var slutet.", t: "كانت المجموعة مغلقة." },
    "UNS": { s: "Inte ett uns sanning.", t: "ولا ذرة من الحقيقة." },
    "SANNA": { s: "Mina drömmar blev sanna.", t: "أصبحت أحلامي حقيقة." },
    "FISKAR": { s: "Han fiskar i sjön.", t: "هو يصطاد في البحيرة." },
    "REST": { s: "Vi åt upp resten av maten.", t: "أكلنا بقية الطعام." },
    "OTAL": { s: "Ett otal gånger.", t: "مرات لا تحصى." },
    "STORM": { s: "Stormen fällde många träd.", t: "أسقطت العاصفة أشجاراً كثيرة." },
    "FAST": { s: "Han satt fast i trafiken.", t: "علق في الازدحام المروري." },
    "NIT": { s: "Det var en nit.", t: "كانت ورقة خاسرة." },
    "PIL": { s: "Han sköt en pil.", t: "أطلق سهماً." },
    "RÖN": { s: "Nya rön om hälsa.", t: "اكتشافات جديدة حول الصحة." },
    "SNÄV": { s: "Kjolen är för snäv.", t: "التنورة ضيقة جداً." },
    "BLODIG": { s: "Biffen var blodig.", t: "شريحة اللحم كانت نيئة." },
    "BILD": { s: "En fin bild på familjen.", t: "صورة جميلة للعائلة." },
    "LIVS": { s: "Det är en livs levande älg.", t: "إنه лось حي يرزق." },
    "SKIT": { s: "Det var bara skit.", t: "كان مجرد هراء." },
    "VECKA": { s: "Vi ses nästa vecka.", t: "نلتقي الأسبوع القادم." },
    "ANING": { s: "Jag har ingen aning.", t: "ليس لدي أي فكرة." },
    "MATT": { s: "Färgen är matt.", t: "اللون باهت." },
    "FIL": { s: "Jag äter fil till frukost.", t: "آكل اللبن الرائب للإفطار." },
    "SUR": { s: "Citronen är sur.", t: "الليمون حامض." },
    "RUS": { s: "Han sov ruset av sig.", t: "نام ليزول عنه السكر." },
    "SUCK": { s: "Hon drog en djup suck.", t: "تنهدت بعمق." },
    "LAX": { s: "Lax är nyttig mat.", t: "السلمون طعام صحي." },
    "RUIN": { s: "Huset är en ruin.", t: "المنزل عبارة عن حطام." },
    "TOK": { s: "Det gick på tok.", t: "سارت الأمور بشكل خاطئ." },
    "SMAL": { s: "Vägen är smal.", t: "الطريق ضيق." },
    "GÅR": { s: "Tiden går fort.", t: "الوقت يمضي بسرعة." },
    "AKT": { s: "Ta dig i akt!", t: "احذر!" },
    "KRAS": { s: "Vasen gick i kras.", t: "تحطمت المزهرية." },
    "RING": { s: "Hon bär en guldring.", t: "هي ترتدي خاتماً ذهبياً." },
    "ÅLIGGER": { s: "Det åligger dig att svara.", t: "يقع على عاتقك الرد." },
    "RIS": { s: "Vi äter ris och kyckling.", t: "نأكل الأرز والدجاج." },
    "LÄN": { s: "Vi bor i Skåne län.", t: "نسكن في محافظة سكونه." },
    "LÄNK": { s: "Klicka på länken.", t: "اضغط على الرابط." },
    "KAN": { s: "Jag kan simma.", t: "أستطيع السباحة." },
    "STILLA": { s: "Havet ligger stilla.", t: "البحر هادئ." },
    "SILL": { s: "Sill är gott.", t: "الرنجة لذيذة." },
    "VIT": { s: "Snön är vit.", t: "الثلج أبيض." },
    "ANTAL": { s: "Ett stort antal fåglar.", t: "عدد كبير من الطيور." },
    "OND": { s: "Han har ont i magen.", t: "لديه ألم في البطن." },
    "ORDNAR": { s: "Jag ordnar festen.", t: "أنا أنظم الحفلة." },
    "NORDLIG": { s: "Vinden är nordlig.", t: "الرياح شمالية." },
    "PORT": { s: "Öppna porten!", t: "افتح البوابة!" },
    "ROT": { s: "Trädet har en djup rot.", t: "للشجرة جذر عميق." },
    "STATY": { s: "En staty av kungen.", t: "تمثال للملك." },
    "VARS": { s: "En man vars bil är röd.", t: "رجل سيارته حمراء." },
    "MOT": { s: "Vi går mot stranden.", t: "نحن ذاهبون نحو الشاطئ." },
    "ROS": { s: "En röd ros doftar gott.", t: "الوردة الحمراء تفوح منها رائحة طيبة." },
    "PLASK": { s: "Det hördes ett plask.", t: "سُمع صوت طرطشة." },
    "OFTAST": { s: "Jag cyklar oftast.", t: "أركب الدراجة غالباً." },
    "SLITEN": { s: "Soffan är sliten.", t: "الأريكة مهترئة." },
    "SKAPLIG": { s: "Vädret är skapligt.", t: "الطقس مقبول." },
    "GAP": { s: "Dörren står på gap.", t: "الباب مفتوح قليلاً." },
    "KIND": { s: "Hon fick en kyss på kinden.", t: "حصلت على قبلة على الخد." },
    "BLOD": { s: "Blodet rinner.", t: "الدم يسيل." },
    "TÄT": { s: "Skogen är tät.", t: "الغابة كثيفة." },
    "VERK": { s: "Det är ett konstverk.", t: "إنه عمل فني." },
    "VIRKE": { s: "Vi behöver virke till huset.", t: "نحتاج خشباً للمنزل." },
    "FLIT": { s: "Han studerar med flit.", t: "هو يدرس بجد." },
    "CIRKUS": { s: "Vi gick på cirkus.", t: "ذهبنا إلى السيرك." },
    "NÄST": { s: "Du är näst på tur.", t: "أنت التالي في الدور." },
    "SÖT": { s: "Kakan är söt.", t: "الكعكة حلوة." },
    "NERE": { s: "Katten är där nere.", t: "القطة هناك في الأسفل." },
    "REGN": { s: "Regnet öser ner.", t: "المطر ينهمر." },
    "MÅTTA": { s: "Allt med måtta.", t: "كل شيء باعتدال." },
    "ANNARS": { s: "Kom nu, annars blir vi sena.", t: "تعال الآن، وإلا سنتأخر." },
    "MAL": { s: "Kvarnen mal säden.", t: "الطاحونة تطحن الحبوب." },
    "RAD": { s: "Stå i en rad.", t: "قف في صف." },
    "KUL": { s: "Det var en kul fest.", t: "كانت حفلة ممتعة." },
    "SVAR": { s: "Jag vill ha ett svar.", t: "أريد جواباً." },
    "PASTOR": { s: "Pastorn talade i kyrkan.", t: "تحدث القس في الكنيسة." },
    "RAGGARE": { s: "Raggare kör gamla bilar.", t: "يقود الـ Raggare سيارات قديمة." },
    "ÄTER": { s: "Han äter ett äpple.", t: "هو يأكل تفاحة." },
    "STÅR": { s: "Bilen står på gatan.", t: "السيارة واقفة في الشارع." },
    "LOTTA": { s: "Lotta är en lottakår.", t: "لوتا هي مجندة متطوعة." },
    "KARL": { s: "Han är en stilig karl.", t: "إنه رجل وسيم." },
    "VERS": { s: "Läs en vers ur boken.", t: "اقرأ بيتاً من الكتاب." },
    "ARG": { s: "Var inte arg på mig.", t: "لا تغضب مني." },
    "KRUS": { s: "Inget krus, tack.", t: "بدون مجاملات، شكراً." },
    "SKUR": { s: "En skur av regn.", t: "زخّة مطر." },
    "RUNA": { s: "En gammal runa på stenen.", t: "حرف رونية قديم على الحجر." },
    "MASKIN": { s: "Maskinen är trasig.", t: "الآلة معطلة." },
    "SKIDA": { s: "Vi åker skidor i fjällen.", t: "نتزلج في الجبال." },
    "SIDA": { s: "Vänd sida i boken.", t: "اقلب الصفحة في الكتاب." },
    "RUND": { s: "Bollen är rund.", t: "الكرة مستديرة." },
    "SOTARE": { s: "Sotaren rensar skorstenen.", t: "منظف المداخن ينظف المدخنة." },
    "VÄNSTER": { s: "Ta till vänster här.", t: "انعطف يساراً هنا." },
    "TORR": { s: "Marken är torr.", t: "الأرض جافة." },
    "DIMMA": { s: "Dimman ligger tät.", t: "الضباب كثيف." },
    "DOMARE": { s: "Domaren blåste i visslan.", t: "نفخ الحكم في الصافرة." },
    "DROPPE": { s: "En droppe vatten.", t: "قطرة ماء." },
    "ENERGI": { s: "Solenergi är bra.", t: "الطاقة الشمسية جيدة." },
    "FACKLA": { s: "Han bar en fackla.", t: "حمل شعلة." },
    "DEBATT": { s: "En livlig debatt.", t: "نقاش حيوي." },
    "CHOCK": { s: "Han fick en chock.", t: "أصيب بصدمة." },
    "BÄRARE": { s: "En bärare av virus.", t: "حامل للفيروس." },
    "DISTANS": { s: "Håll distans.", t: "حافظ على المسافة." },
    "TRAFIK": { s: "Mycket trafik idag.", t: "حركة مرور كثيفة اليوم." },
    "GATA": { s: "Gatan är lång.", t: "الشارع طويل." },
    "TORG": { s: "Vi möts på torget.", t: "نلتقي في الساحة." },
    "STAD": { s: "En stor stad.", t: "مدينة كبيرة." },
    "FÅGEL": { s: "Fågeln flyger högt.", t: "الطائر يطير عالياً." },
    "HÄST": { s: "Hästen springer fort.", t: "الحصان يركض بسرعة." },
    "HUND": { s: "Hunden skäller.", t: "الكلب ينبح." },
    "KATT": { s: "Katten jamar.", t: "القطة تموء." },
    "MATTA": { s: "En mjuk matta.", t: "سجادة ناعمة." },
    "MÖBEL": { s: "En fin möbel.", t: "قطعة أثاث جميلة." },
    "FÖNSTER": { s: "Öppna fönstret.", t: "افتح النافذة." },
    "DÖRR": { s: "Stäng dörren.", t: "أغلق الباب." }
};

module.exports = MANUAL_SENTENCES;
