// ========================================
//  SWEDISH WORD CONNECT DATA
// ========================================

// Pre-defined levels to ensure exact difficulty curve
const WC_PREDEFINED_LEVELS = {
    // --- CHAPTER 1: Introduction (Max 3 letters, 1-3 words) ---
    "1-1": { letters: ["H", "E", "J"], words: ["HEJ"], validWords: ["HEJ"] },
    "1-2": { letters: ["B", "O", "R"], words: ["BOR", "RO"], validWords: ["BOR", "RO"] },
    "1-3": { letters: ["S", "E", "R"], words: ["SER", "SE", "ER"], validWords: ["SER", "SE", "ER"] },
    "1-4": { letters: ["T", "Å", "G"], words: ["TÅG", "GÅ"], validWords: ["TÅG", "GÅ"] },
    "1-5": { letters: ["S", "N", "Ö"], words: ["SNÖ"], validWords: ["SNÖ"] },
    "1-6": { letters: ["B", "I", "L"], words: ["BIL", "IL", "LI"], validWords: ["BIL", "IL", "LI"] },
    "1-7": { letters: ["K", "O", "M"], words: ["KOM", "OM"], validWords: ["KOM", "OM"] },
    "1-8": { letters: ["D", "A", "G"], words: ["DAG", "GA"], validWords: ["DAG", "GA"] },
    "1-9": { letters: ["S", "O", "L"], words: ["SOL", "OS"], validWords: ["SOL", "OS"] },
    "1-10": { letters: ["H", "A", "V"], words: ["HAV", "AV"], validWords: ["HAV", "AV"] },

    // --- CHAPTER 2: Beginner (Max 3 letters, EXACTLY 3 words) ---
    "2-1": { letters: ["T", "Å", "G"], words: ["TÅG", "TÅ", "GÅ"], validWords: ["TÅG", "TÅ", "GÅ"] },
    "2-2": { letters: ["B", "O", "K"], words: ["BOK", "BO", "OK"], validWords: ["BOK", "BO", "OK"] },
    "2-3": { letters: ["L", "Å", "S"], words: ["LÅS", "SÅ", "ÅL"], validWords: ["LÅS", "SÅ", "ÅL"] },
    "2-4": { letters: ["N", "Å", "L"], words: ["NÅL", "NÅ", "LÅN"], validWords: ["NÅL", "NÅ", "LÅN"] },
    "2-5": { letters: ["R", "Å", "D"], words: ["RÅD", "RÅ", "DÅ"], validWords: ["RÅD", "RÅ", "DÅ"] },
    "2-6": { letters: ["R", "O", "M"], words: ["ROM", "ORM", "MOR"], validWords: ["ROM", "ORM", "MOR"] },
    "2-7": { letters: ["O", "S", "T"], words: ["OST", "SOT", "STO"], validWords: ["OST", "SOT", "STO"] },
    "2-8": { letters: ["A", "L", "M"], words: ["ALM", "MAL", "LAM"], validWords: ["ALM", "MAL", "LAM"] },
    "2-9": { letters: ["A", "R", "T"], words: ["ART", "TAR", "RAT"], validWords: ["ART", "TAR", "RAT"] },
    "2-10": { letters: ["V", "A", "R"], words: ["VAR", "ARV", "RAV"], validWords: ["VAR", "ARV", "RAV"] },

    // --- CHAPTER 3: Easy (4 letters) ---
    "3-1": { letters: ["B", "O", "R", "D"], words: ["BORD", "BOR", "RO"], validWords: ["BORD", "BOR", "RO"] },
    "3-2": { letters: ["S", "T", "O", "L"], words: ["STOL", "SOL", "OS"], validWords: ["STOL", "SOL", "OS"] },
    "3-3": { letters: ["G", "L", "A", "D"], words: ["GLAD", "LAG", "DAL"], validWords: ["GLAD", "LAG", "DAL"] },
    "3-4": { letters: ["P", "R", "A", "T"], words: ["PRAT", "PAR", "ART"], validWords: ["PRAT", "PAR", "ART"] },
    "3-5": { letters: ["K", "O", "R", "T"], words: ["KORT", "ORT", "RO"], validWords: ["KORT", "ORT", "RO"] },
    "3-6": { letters: ["L", "A", "N", "D"], words: ["LAND", "DAL", "DAN"], validWords: ["LAND", "DAL", "DAN"] },
    "3-7": { letters: ["H", "A", "N", "D"], words: ["HAND", "HAN", "DAN"], validWords: ["HAND", "HAN", "DAN"] },
    "3-8": { letters: ["B", "I", "L", "D"], words: ["BILD", "BIL", "LID"], validWords: ["BILD", "BIL", "LID"] },
    "3-9": { letters: ["V", "A", "R", "M"], words: ["VARM", "VAR", "ARM"], validWords: ["VARM", "VAR", "ARM"] },
    "3-10": { letters: ["K", "A", "L", "L"], words: ["KALL", "ALL", "KAL"], validWords: ["KALL", "ALL", "KAL"] },

    // --- CHAPTER 4: Medium (4-5 letters) ---
    "4-1": { letters: ["S", "K", "O", "L", "A"], words: ["SKOLA", "SKAL", "SOL", "KO"], validWords: ["SKOLA", "SKAL", "SOL", "KO"] },
    "4-2": { letters: ["K", "A", "R", "T", "A"], words: ["KARTA", "ART", "RAK", "TA"], validWords: ["KARTA", "ART", "RAK", "TA"] },
    "4-3": { letters: ["L", "I", "S", "T", "A"], words: ["LISTA", "SILA", "SAL", "IS"], validWords: ["LISTA", "SILA", "SAL", "IS"] },
    "4-4": { letters: ["P", "O", "S", "T", "A"], words: ["POSTA", "POST", "OS", "TA"], validWords: ["POSTA", "POST", "OS", "TA"] },
    "4-5": { letters: ["T", "V", "Ä", "T", "T"], words: ["TVÄTT", "TV", "ÄT"], validWords: ["TVÄTT", "TV", "ÄT"] },
    "4-6": { letters: ["C", "Y", "K", "E", "L"], words: ["CYKEL", "KYL", "LEK"], validWords: ["CYKEL", "KYL", "LEK"] },
    "4-7": { letters: ["F", "Å", "G", "E", "L"], words: ["FÅGEL", "LÅG", "FEL"], validWords: ["FÅGEL", "LÅG", "FEL"] },
    "4-8": { letters: ["D", "A", "T", "O", "R"], words: ["DATOR", "RAD", "ROT", "TA"], validWords: ["DATOR", "RAD", "ROT", "TA"] },
    "4-9": { letters: ["P", "A", "K", "E", "T"], words: ["PAKET", "TAK", "EK"], validWords: ["PAKET", "TAK", "EK"] },
    "4-10": { letters: ["R", "A", "D", "I", "O"], words: ["RADIO", "RAD", "RO", "DÅ"], validWords: ["RADIO", "RAD", "RO", "DÅ"] },

    // --- CHAPTER 5: Hard (5 letters) ---
    "5-1": { letters: ["P", "E", "N", "N", "A"], words: ["PENNA", "PANN", "EN"], validWords: ["PENNA", "PANN", "EN"] },
    "5-2": { letters: ["V", "Ä", "S", "K", "A"], words: ["VÄSKA", "VÄK", "SAK"], validWords: ["VÄSKA", "VÄK", "SAK"] },
    "5-3": { letters: ["L", "A", "M", "P", "A"], words: ["LAMPA", "PALM", "MAL"], validWords: ["LAMPA", "PALM", "MAL"] },
    "5-4": { letters: ["M", "A", "T", "T", "A"], words: ["MATTA", "MAT", "ATT"], validWords: ["MATTA", "MAT", "ATT"] },
    "5-5": { letters: ["S", "O", "F", "F", "A"], words: ["SOFFA", "OSA", "FA"], validWords: ["SOFFA", "OSA", "FA"] },
    "5-6": { letters: ["K", "U", "D", "D", "E"], words: ["KUDDE", "UDD", "DU"], validWords: ["KUDDE", "UDD", "DU"] },
    "5-7": { letters: ["T", "A", "V", "L", "A"], words: ["TAVLA", "VAL", "TAL"], validWords: ["TAVLA", "VAL", "TAL"] },
    "5-8": { letters: ["H", "Y", "L", "L", "A"], words: ["HYLLA", "HALL", "HY"], validWords: ["HYLLA", "HALL", "HY"] },
    "5-9": { letters: ["G", "R", "Ö", "N", "A"], words: ["GRÖNA", "GRÖN", "ÖRN"], validWords: ["GRÖNA", "GRÖN", "ÖRN"] },
    "5-10": { letters: ["S", "V", "A", "R", "T"], words: ["SVART", "VAR", "ARV"], validWords: ["SVART", "VAR", "ARV"] },

    // --- CHAPTER 6: Advanced (5-6 letters) ---
    "6-1": { letters: ["S", "O", "M", "M", "A", "R"], words: ["SOMMAR", "SOM", "MOR", "RAM", "ROM"], validWords: ["SOMMAR", "SOM", "MOR", "RAM", "ROM"] },
    "6-2": { letters: ["V", "I", "N", "T", "E", "R"], words: ["VINTER", "VIN", "REN", "TRE"], validWords: ["VINTER", "VIN", "REN", "TRE"] },
    "6-3": { letters: ["H", "Ö", "S", "T", "E", "N"], words: ["HÖSTEN", "HÖST", "SEN", "TEN"], validWords: ["HÖSTEN", "HÖST", "SEN", "TEN"] },
    "6-4": { letters: ["V", "Å", "R", "E", "N"], words: ["VÅREN", "VÅR", "REN", "EN"], validWords: ["VÅREN", "VÅR", "REN", "EN"] },
    "6-5": { letters: ["F", "L", "I", "C", "K", "A"], words: ["FLICKA", "LACK", "FIL"], validWords: ["FLICKA", "LACK", "FIL"] },
    "6-6": { letters: ["P", "O", "J", "K", "E"], words: ["POJKE", "OK", "KO"], validWords: ["POJKE", "OK", "KO"] },
    "6-7": { letters: ["L", "Ä", "R", "A", "R", "E"], words: ["LÄRARE", "LÄRA", "RER"], validWords: ["LÄRARE", "LÄRA", "RER"] },
    "6-8": { letters: ["E", "L", "E", "V", "E", "N"], words: ["ELEVEN", "ELEV", "LEV"], validWords: ["ELEVEN", "ELEV", "LEV"] },
    "6-9": { letters: ["S", "K", "O", "L", "A", "N"], words: ["SKOLAN", "SKOLA", "SKAL", "SOL"], validWords: ["SKOLAN", "SKOLA", "SKAL", "SOL"] },
    "6-10": { letters: ["K", "L", "A", "S", "S"], words: ["KLASS", "LASS", "SAL"], validWords: ["KLASS", "LASS", "SAL"] },

    // --- CHAPTER 7: Expert (6 letters) ---
    "7-1": { letters: ["F", "A", "M", "I", "L", "J"], words: ["FAMILJ", "MIL", "FIL"], validWords: ["FAMILJ", "MIL", "FIL"] },
    "7-2": { letters: ["S", "Y", "S", "T", "E", "R"], words: ["SYSTER", "SYR", "SER"], validWords: ["SYSTER", "SYR", "SER"] },
    "7-3": { letters: ["B", "R", "O", "D", "E", "R"], words: ["BRODER", "BROR", "RODER", "RO"], validWords: ["BRODER", "BROR", "RODER", "RO"] },
    "7-4": { letters: ["D", "O", "T", "T", "E", "R"], words: ["DOTTER", "ROTE", "TRE"], validWords: ["DOTTER", "ROTE", "TRE"] },
    "7-5": { letters: ["M", "O", "R", "F", "A", "R"], words: ["MORFAR", "MOR", "FAR", "RAM"], validWords: ["MORFAR", "MOR", "FAR", "RAM"] },
    "7-6": { letters: ["F", "A", "R", "M", "O", "R"], words: ["FARMOR", "FAR", "MOR", "ROM"], validWords: ["FARMOR", "FAR", "MOR", "ROM"] },
    "7-7": { letters: ["K", "U", "S", "I", "N"], words: ["KUSIN", "SIN", "IS"], validWords: ["KUSIN", "SIN", "IS"] },
    "7-8": { letters: ["V", "Ä", "N", "N", "E", "N"], words: ["VÄNNEN", "VÄN", "EN"], validWords: ["VÄNNEN", "VÄN", "EN"] },
    "7-9": { letters: ["G", "R", "A", "N", "N"], words: ["GRANN", "GRAN", "RAN"], validWords: ["GRANN", "GRAN", "RAN"] },
    "7-10": { letters: ["S", "L", "Ä", "K", "T"], words: ["SLÄKT", "LÄK", "TÅ"], validWords: ["SLÄKT", "LÄK", "TÅ"] },

    // --- CHAPTER 8: Master (6-7 letters) ---
    "8-1": { letters: ["F", "R", "U", "K", "O", "S", "T"], words: ["FRUKOST", "FRU", "KOST", "ROST", "OST"], validWords: ["FRUKOST", "FRU", "KOST", "ROST", "OST"] },
    "8-2": { letters: ["M", "I", "D", "D", "A", "G"], words: ["MIDDAG", "DAG", "IDAG", "MIG"], validWords: ["MIDDAG", "DAG", "IDAG", "MIG"] },
    "8-3": { letters: ["K", "V", "Ä", "L", "L"], words: ["KVÄLL", "VÄL", "KÄL"], validWords: ["KVÄLL", "VÄL", "KÄL"] },
    "8-4": { letters: ["M", "A", "T", "E", "N"], words: ["MATEN", "MAT", "TEN", "EN"], validWords: ["MATEN", "MAT", "TEN", "EN"] },
    "8-5": { letters: ["V", "A", "T", "T", "E", "N"], words: ["VATTEN", "VATT", "TEN", "ATT"], validWords: ["VATTEN", "VATT", "TEN", "ATT"] },
    "8-6": { letters: ["K", "A", "F", "F", "E"], words: ["KAFFE", "FE", "AK"], validWords: ["KAFFE", "FE", "AK"] },
    "8-7": { letters: ["M", "J", "Ö", "L", "K"], words: ["MJÖLK", "MÖ", "KÖL"], validWords: ["MJÖLK", "MÖ", "KÖL"] },
    "8-8": { letters: ["S", "O", "C", "K", "E", "R"], words: ["SOCKER", "SOCK", "ROCK", "ROS", "KO"], validWords: ["SOCKER", "SOCK", "ROCK", "ROS", "KO"] },
    "8-9": { letters: ["P", "E", "P", "P", "A", "R"], words: ["PEPPAR", "PAPPA", "PAR"], validWords: ["PEPPAR", "PAPPA", "PAR"] },
    "8-10": { letters: ["S", "A", "L", "T", "E", "T"], words: ["SALTET", "SALT", "TAL", "LET"], validWords: ["SALTET", "SALT", "TAL", "LET"] },

    // --- CHAPTER 9: Grandmaster (7 letters) ---
    "9-1": { letters: ["T", "E", "L", "E", "F", "O", "N"], words: ["TELEFON", "TELE", "FEL", "TON", "EN"], validWords: ["TELEFON", "TELE", "FEL", "TON", "EN"] },
    "9-2": { letters: ["M", "O", "B", "I", "L", "E", "N"], words: ["MOBILEN", "MOBIL", "BIL", "MIL", "LEN"], validWords: ["MOBILEN", "MOBIL", "BIL", "MIL", "LEN"] },
    "9-3": { letters: ["D", "A", "T", "O", "R", "N"], words: ["DATORN", "DATOR", "ROT", "TON", "RAD"], validWords: ["DATORN", "DATOR", "ROT", "TON", "RAD"] },
    "9-4": { letters: ["S", "K", "Ä", "R", "M", "E", "N"], words: ["SKÄRMEN", "SKÄRM", "MÄN", "REN"], validWords: ["SKÄRMEN", "SKÄRM", "MÄN", "REN"] },
    "9-5": { letters: ["M", "U", "S", "I", "K", "E", "N"], words: ["MUSIKEN", "MUSIK", "MUS", "IS", "EN"], validWords: ["MUSIKEN", "MUSIK", "MUS", "IS", "EN"] },
    "9-6": { letters: ["F", "I", "L", "M", "E", "N"], words: ["FILMEN", "FILM", "FIL", "MEN", "LEN"], validWords: ["FILMEN", "FILM", "FIL", "MEN", "LEN"] },
    "9-7": { letters: ["B", "O", "K", "E", "N"], words: ["BOKEN", "BOK", "BEN", "KO", "EN"], validWords: ["BOKEN", "BOK", "BEN", "KO", "EN"] },
    "9-8": { letters: ["T", "I", "D", "N", "I", "N", "G"], words: ["TIDNING", "TID", "NING", "DIN", "IN"], validWords: ["TIDNING", "TID", "NING", "DIN", "IN"] },
    "9-9": { letters: ["P", "E", "N", "N", "A", "N"], words: ["PENNAN", "PENNA", "PANN", "EN"], validWords: ["PENNAN", "PENNA", "PANN", "EN"] },
    "9-10": { letters: ["P", "A", "P", "P", "E", "R"], words: ["PAPPER", "PAPP", "PAR", "RE"], validWords: ["PAPPER", "PAPP", "PAR", "RE"] },

    // --- CHAPTER 10: Legend (7+ letters) ---
    "10-1": { letters: ["S", "J", "U", "K", "H", "U", "S"], words: ["SJUKHUS", "SJUK", "HUS", "US"], validWords: ["SJUKHUS", "SJUK", "HUS", "US"] },
    "10-2": { letters: ["D", "O", "K", "T", "O", "R", "N"], words: ["DOKTORN", "DOKTOR", "TOR", "ROT", "KOR"], validWords: ["DOKTORN", "DOKTOR", "TOR", "ROT", "KOR"] },
    "10-3": { letters: ["A", "P", "O", "T", "E", "K"], words: ["APOTEK", "POT", "TE", "EK"], validWords: ["APOTEK", "POT", "TE", "EK"] },
    "10-4": { letters: ["M", "E", "D", "I", "C", "I", "N"], words: ["MEDICIN", "MED", "DIN", "IS"], validWords: ["MEDICIN", "MED", "DIN", "IS"] },
    "10-5": { letters: ["P", "O", "L", "I", "S", "E", "N"], words: ["POLISEN", "POLIS", "SOL", "IS", "LEN"], validWords: ["POLISEN", "POLIS", "SOL", "IS", "LEN"] },
    "10-6": { letters: ["B", "R", "A", "N", "D", "E", "N"], words: ["BRANDEN", "BRAND", "AND", "DEN", "REN"], validWords: ["BRANDEN", "BRAND", "AND", "DEN", "REN"] },
    "10-7": { letters: ["H", "J", "Ä", "L", "P", "E", "N"], words: ["HJÄLPEN", "HJÄLP", "LÄN", "EN"], validWords: ["HJÄLPEN", "HJÄLP", "LÄN", "EN"] },
    "10-8": { letters: ["O", "L", "Y", "C", "K", "A"], words: ["OLYCKA", "LYCKA", "OCK", "AL"], validWords: ["OLYCKA", "LYCKA", "OCK", "AL"] },
    "10-9": { letters: ["R", "Ä", "D", "D", "A"], words: ["RÄDDA", "RÄDD", "DÅ"], validWords: ["RÄDDA", "RÄDD", "DÅ"] },
    "10-10": { letters: ["T", "R", "Y", "G", "G"], words: ["TRYGG", "RYGG", "TYG"], validWords: ["TRYGG", "RYGG", "TYG"] }
};

// Curated Dictionary for Dynamic Generation (Chapters 3+) & Translations
const WC_DICTIONARY = [
    // --- CHAPTER 1 & 2 WORDS ---
    { w: "HEJ", t: "مرحباً", s: "Hej, hur mår du?" },
    { w: "BOR", t: "يسكن", s: "Jag bor i Stockholm." },
    { w: "RO", t: "هدوء", s: "Jag vill ha lugn och ro." },
    { w: "SER", t: "يرى", s: "Jag ser en fågel." },
    { w: "SE", t: "انظر", s: "Se upp!" },
    { w: "ER", t: "أنتم/لكم", s: "Boken är er." },
    { w: "TÅG", t: "قطار", s: "Vi åker tåg." },
    { w: "GÅ", t: "يمشي", s: "Vi ska gå hem." },
    { w: "TÅ", t: "إصبع القدم", s: "Jag slog min tå." },
    { w: "SNÖ", t: "ثلج", s: "Det snöar idag." },
    { w: "BIL", t: "سيارة", s: "Jag har en bil." },
    { w: "IL", t: "سرعة/عجلة", s: "I full il." },
    { w: "LI", t: "منجل", s: "Lien är vass." },
    { w: "KOM", t: "تعال", s: "Kom hit!" },
    { w: "OM", t: "عن/إذا", s: "Berätta om dig själv." },
    { w: "DAG", t: "يوم", s: "En fin dag." },
    { w: "GA", t: "أعطى (قديم)", s: "Han ga mig boken." },
    { w: "SOL", t: "شمس", s: "Solen skiner." },
    { w: "OS", t: "دخان/رائحة", s: "Det luktar os från köket." },
    { w: "HAV", t: "بحر", s: "Vi badar i havet." },
    { w: "AV", t: "من/عن", s: "Boken är av papper." },
    { w: "BOK", t: "كتاب", s: "Jag läser en bok." },
    { w: "BO", t: "يسكن", s: "Var ska vi bo?" },
    { w: "OK", t: "حسناً/نير", s: "Det är ok." },
    { w: "LÅS", t: "قفل", s: "Dörren har ett lås." },
    { w: "SÅ", t: "هكذا/زرع", s: "Gör så här." },
    { w: "ÅL", t: "ثعبان البحر", s: "Ålen simmar." },
    { w: "NÅL", t: "إبرة", s: "Sy med en nål." },
    { w: "NÅ", t: "يصل", s: "Kan du nå boken?" },
    { w: "LÅN", t: "قرض", s: "Jag tog ett lån." },
    { w: "RÅD", t: "نصيحة", s: "Ge mig ett råd." },
    { w: "RÅ", t: "نيء/يملك", s: "Fisken är rå." },
    { w: "DÅ", t: "حينئذ", s: "Vi ses då." },
    { w: "ROM", t: "روما/بطارخ", s: "Alla vägar bär till Rom." },
    { w: "ORM", t: "ثعبان", s: "Jag såg en orm." },
    { w: "MOR", t: "أم", s: "Min mor är snäll." },
    { w: "OST", t: "جبن", s: "Osten är god." },
    { w: "SOT", t: "سخام", s: "Det är sot i skorstenen." },
    { w: "STO", t: "فرس", s: "Stoet betar i hagen." },
    { w: "ALM", t: "شجر الدردار", s: "En stor alm." },
    { w: "MAL", t: "عثة/سمكة", s: "Malen åt hål i tröjan." },
    { w: "LAM", t: "أعرج/مشلول", s: "Han blev lam i benet." },
    { w: "ART", t: "نوع/فصيلة", s: "En sällsynt art." },
    { w: "TAR", t: "يأخذ", s: "Han tar bussen." },
    { w: "RAT", t: "عجلة القيادة", s: "Håll i ratten." },
    { w: "VAR", t: "أين/كان", s: "Var är du?" },
    { w: "ARV", t: "إرث", s: "Ett stort arv." },
    { w: "RAV", t: "كهرمان", s: "Smycket är av rav." },

    // --- CHAPTER 3+ WORDS ---
    { w: "BORD", t: "طاولة", s: "Maten står på bordet." },
    { w: "STOL", t: "كرسي", s: "Sitt på en stol." },
    { w: "GLAD", t: "سعيد", s: "Jag är glad." },
    { w: "LAG", t: "فريق/قانون", s: "Vi är ett lag." },
    { w: "DAL", t: "وادي", s: "Huset ligger i en dal." },
    { w: "PRAT", t: "حديث", s: "Mycket prat." },
    { w: "PAR", t: "زوج", s: "Ett par skor." },
    { w: "KORT", t: "قصير/بطاقة", s: "Filmen var kort." },
    { w: "ORT", t: "منطقة", s: "En liten ort." },
    { w: "LAND", t: "بلد", s: "Sverige är ett land." },
    { w: "DAN", t: "اليوم (عامية)", s: "Hela dan." },
    { w: "HAND", t: "يد", s: "Ge mig din hand." },
    { w: "HAN", t: "هو", s: "Han är snäll." },
    { w: "BILD", t: "صورة", s: "En fin bild." },
    { w: "LID", t: "منحدر", s: "Backen är en lid." },
    { w: "VARM", t: "دافئ", s: "Solen är varm." },
    { w: "ARM", t: "ذراع", s: "Min arm gör ont." },
    { w: "KALL", t: "بارد", s: "Vattnet är kallt." },
    { w: "ALL", t: "كل", s: "All mat är slut." },
    { w: "KAL", t: "أصلع/عاري", s: "Trädet är kalt." },
    { w: "SKOLA", t: "مدرسة", s: "Jag går i skolan." },
    { w: "SKAL", t: "قشرة", s: "Äpplet har skal." },
    { w: "KO", t: "بقرة", s: "Kon betar gräs." },
    { w: "KARTA", t: "خريطة", s: "Titta på kartan." },
    { w: "RAK", t: "مستقيم", s: "Vägen är rak." },
    { w: "TA", t: "يأخذ", s: "Ta en kaka." },
    { w: "LISTA", t: "قائمة", s: "Skriv en lista." },
    { w: "SILA", t: "يصفّي", s: "Sila soppan." },
    { w: "SAL", t: "قاعة", s: "En stor sal." },
    { w: "IS", t: "جليد", s: "Isen smälter." },
    { w: "POSTA", t: "يرسل بالبريد", s: "Jag ska posta brevet." },
    { w: "POST", t: "بريد", s: "Hämta posten." },
    { w: "TVÄTT", t: "غسيل", s: "Häng upp tvätten." },
    { w: "TV", t: "تلفاز", s: "Titta på TV." },
    { w: "ÄT", t: "كُل", s: "Ät maten." },
    { w: "CYKEL", t: "دراجة", s: "Jag har en cykel." },
    { w: "KYL", t: "ثلاجة/برد", s: "Ställ mjölken i kylen." },
    { w: "LEK", t: "لعب", s: "Lek och skoj." },
    { w: "FÅGEL", t: "طائر", s: "En liten fågel." },
    { w: "LÅG", t: "منخفض/استلقى", s: "Solen stod lågt." },
    { w: "FEL", t: "خطأ", s: "Det blev fel." },
    { w: "DATOR", t: "حاسوب", s: "Min dator är snabb." },
    { w: "RAD", t: "صف", s: "Stå på rad." },
    { w: "ROT", t: "جذر", s: "Trädets rot." },
    { w: "PAKET", t: "حزمة/طرد", s: "Ett stort paket." },
    { w: "TAK", t: "سقف", s: "Taket läcker." },
    { w: "EK", t: "بلوط", s: "En stor ek." },
    { w: "RADIO", t: "مذياع", s: "Lyssna på radio." },
    { w: "PENNA", t: "قلم", s: "Jag behöver en penna." },
    { w: "PANN", t: "جبهة (جزء)", s: "Pannan är varm." },
    { w: "EN", t: "واحد/شجرة عرعر", s: "En fin dag." },
    { w: "VÄSKA", t: "حقيبة", s: "Min väska är tung." },
    { w: "VÄK", t: "ثقب (في الجليد)", s: "En vak i isen." },
    { w: "SAK", t: "شيء", s: "En viktig sak." },
    { w: "LAMPA", t: "مصباح", s: "Tänd lampan." },
    { w: "PALM", t: "نخلة", s: "En hög palm." },
    { w: "MATTA", t: "سجادة", s: "En mjuk matta." },
    { w: "MAT", t: "طعام", s: "Maten är klar." },
    { w: "ATT", t: "أن", s: "Roligt att se dig." },
    { w: "SOFFA", t: "أريكة", s: "Sitt i soffan." },
    { w: "OSA", t: "تفوح رائحة", s: "Det osar mat." },
    { w: "FA", t: "درجة (موسيقى)", s: "Do re mi fa." },
    { w: "KUDDE", t: "وسادة", s: "En mjuk kudde." },
    { w: "UDD", t: "رأس (جغرافي)", s: "En udde i sjön." },
    { w: "DU", t: "أنت", s: "Hur mår du?" },
    { w: "TAVLA", t: "لوحة", s: "En fin tavla." },
    { w: "VAL", t: "خيار/حوت", s: "Gör ett val." },
    { w: "TAL", t: "خطاب/عدد", s: "Håll ett tal." },
    { w: "HYLLA", t: "رف", s: "Boken står på hyllan." },
    { w: "HALL", t: "صالة/مدخل", s: "Skorna står i hallen." },
    { w: "HY", t: "بشرة", s: "Fin hy." },
    { w: "GRÖNA", t: "خضراء", s: "Gröna blad." },
    { w: "GRÖN", t: "أخضر", s: "Gräset är grönt." },
    { w: "ÖRN", t: "نسر", s: "En stor örn." },
    { w: "SVART", t: "أسود", s: "Katten är svart." },
    { w: "SOMMAR", t: "صيف", s: "Det är sommar." },
    { w: "SOM", t: "الذي/مثل", s: "Du är som jag." },
    { w: "RAM", t: "إطار", s: "En fin ram." },
    { w: "VINTER", t: "شتاء", s: "Det är vinter." },
    { w: "VIN", t: "نبيذ", s: "Rött vin." },
    { w: "REN", t: "نظيف/رنة", s: "Rummet är rent." },
    { w: "TRE", t: "ثلاثة", s: "Ett två tre." },
    { w: "HÖSTEN", t: "الخريف", s: "Hösten är vacker." },
    { w: "HÖST", t: "خريف", s: "I höst." },
    { w: "SEN", t: "متأخر", s: "Klockan är sen." },
    { w: "TEN", t: "قصدير", s: "Gjord av ten." },
    { w: "VÅREN", t: "الربيع", s: "Våren är här." },
    { w: "VÅR", t: "ربيع/لنا", s: "Det är vår bil." },
    { w: "FLICKA", t: "فتاة", s: "En liten flicka." },
    { w: "LACK", t: "طلاء", s: "Rött lack." },
    { w: "FIL", t: "لبن رائب/مبرد/ملف", s: "Äta fil." },
    { w: "POJKE", t: "فتى", s: "En liten pojke." },
    { w: "LÄRARE", t: "معلم", s: "Min lärare är bra." },
    { w: "LÄRA", t: "يعلّم/يتعلّم", s: "Att lära sig." },
    { w: "RER", t: "ينقّي (نادر)", s: "Rer ut garnet." },
    { w: "ELEVEN", t: "التلميذ", s: "Eleven läser." },
    { w: "ELEV", t: "تلميذ", s: "En ny elev." },
    { w: "LEV", t: "رغيف/عِش", s: "Lev ditt liv." },
    { w: "SKOLAN", t: "المدرسة", s: "Gå till skolan." },
    { w: "KLASS", t: "صف", s: "Min klass." },
    { w: "LASS", t: "حمل", s: "Ett lass ved." },
    { w: "FAMILJ", t: "عائلة", s: "Min familj." },
    { w: "MIL", t: "ميل (10 كم)", s: "En mil kvar." },
    { w: "SYSTER", t: "أخت", s: "Min syster." },
    { w: "SYR", t: "يخيط", s: "Hon syr en klänning." },
    { w: "BRODER", t: "أخ (رسمي)", s: "Kära broder." },
    { w: "BROR", t: "أخ", s: "Min bror." },
    { w: "RODER", t: "دفة", s: "Båtens roder." },
    { w: "DOTTER", t: "ابنة", s: "Min dotter." },
    { w: "ROTE", t: "فصيلة/جذر", s: "En rote soldater." },
    { w: "MORFAR", t: "جد (أب الأم)", s: "Min morfar." },
    { w: "FAR", t: "أب", s: "Min far." },
    { w: "FARMOR", t: "جدة (أم الأب)", s: "Min farmor." },
    { w: "KUSIN", t: "ابن العم/الخال", s: "Min kusin." },
    { w: "SIN", t: "الخاص به", s: "Han tog sin hatt." },
    { w: "VÄNNEN", t: "الصديق", s: "Vännen kom hit." },
    { w: "VÄN", t: "صديق", s: "En god vän." },
    { w: "GRANN", t: "جميل/جار", s: "Grannlåt." },
    { w: "GRAN", t: "شجرة تنوب", s: "En grön gran." },
    { w: "RAN", t: "سرقة (قديم)", s: "Rån och ran." },
    { w: "SLÄKT", t: "أقارب", s: "Hela släkten." },
    { w: "LÄK", t: "اشفِ", s: "Läk såret." },
    { w: "FRUKOST", t: "فطور", s: "Äta frukost." },
    { w: "FRU", t: "زوجة/سيدة", s: "Min fru." },
    { w: "KOST", t: "غذاء/تكلفة", s: "God kost." },
    { w: "ROST", t: "صدأ", s: "Rost på bilen." },
    { w: "MIDDAG", t: "عشاء", s: "Äta middag." },
    { w: "IDAG", t: "اليوم", s: "Kom idag." },
    { w: "MIG", t: "أنا (مفعول)", s: "Se på mig." },
    { w: "KVÄLL", t: "مساء", s: "I kväll." },
    { w: "VÄL", t: "حسناً/جيداً", s: "Det går väl bra." },
    { w: "KÄL", t: "وتد (نادر)", s: "En käl." },
    { w: "MATEN", t: "الطعام", s: "Maten är god." },
    { w: "TEN", t: "قصدير/محور", s: "En ten." },
    { w: "VATTEN", t: "ماء", s: "Dricka vatten." },
    { w: "VATT", t: "واط (كهرباء)", s: "100 watt." },
    { w: "KAFFE", t: "قهوة", s: "Dricka kaffe." },
    { w: "FE", t: "جنية", s: "En god fe." },
    { w: "AK", t: "مؤخرة (سفينة)", s: "Akter." },
    { w: "MJÖLK", t: "حليب", s: "Dricka mjölk." },
    { w: "MÖ", t: "عذراء (قديم)", s: "En vacker mö." },
    { w: "KÖL", t: "عارضة السفينة", s: "Båtens köl." },
    { w: "SOCKER", t: "سكر", s: "Sött socker." },
    { w: "SOCK", t: "جورب (عامية)", s: "En socka." },
    { w: "ROCK", t: "معطف/موسيقى", s: "En varm rock." },
    { w: "ROS", t: "وردة", s: "En röd ros." },
    { w: "PEPPAR", t: "فلفل", s: "Salt och peppar." },
    { w: "PAPPA", t: "أبي", s: "Min pappa." },
    { w: "SALTET", t: "الملح", s: "Räck mig saltet." },
    { w: "SALT", t: "ملح", s: "Mat utan salt." },
    { w: "LET", t: "بحث (قديم)", s: "Letade." },
    { w: "TELEFON", t: "هاتف", s: "Svara i telefon." },
    { w: "TELE", t: "عن بعد", s: "Teleobjektiv." },
    { w: "TON", t: "نغمة/طن", s: "En hög ton." },
    { w: "MOBILEN", t: "الجوال", s: "Var är mobilen?" },
    { w: "MOBIL", t: "جوال/متحرك", s: "En mobil telefon." },
    { w: "LEN", t: "ناعم", s: "Len hud." },
    { w: "DATORN", t: "الحاسوب", s: "Datorn är på." },
    { w: "SKÄRMEN", t: "الشاشة", s: "Titta på skärmen." },
    { w: "SKÄRM", t: "شاشة", s: "En stor skärm." },
    { w: "MÄN", t: "رجال", s: "Två män." },
    { w: "MUSIKEN", t: "الموسيقى", s: "Musiken spelar." },
    { w: "MUSIK", t: "موسيقى", s: "Jag gillar musik." },
    { w: "MUS", t: "فأر", s: "En liten mus." },
    { w: "FILMEN", t: "الفيلم", s: "Filmen var bra." },
    { w: "FILM", t: "فيلم", s: "Se på film." },
    { w: "MEN", t: "لكن", s: "Ja, men..." },
    { w: "BOKEN", t: "الكتاب", s: "Boken är bra." },
    { w: "BEN", t: "ساق/عظم", s: "Bryta benet." },
    { w: "TIDNING", t: "جريدة", s: "Läsa tidning." },
    { w: "TID", t: "وقت", s: "Vad är det för tid?" },
    { w: "NING", t: "لاحقة (قواعد)", s: "Ändelse." },
    { w: "DIN", t: "لك", s: "Är det din?" },
    { w: "IN", t: "داخل", s: "Kom in." },
    { w: "PENNAN", t: "القلم", s: "Här är pennan." },
    { w: "PAPPER", t: "ورق", s: "Skriv på papper." },
    { w: "PAPP", t: "ورق مقوى", s: "En låda av papp." },
    { w: "RE", t: "نوتة ري", s: "Do re mi." },
    { w: "SJUKHUS", t: "مستشفى", s: "Åka till sjukhus." },
    { w: "SJUK", t: "مريض", s: "Jag är sjuk." },
    { w: "HUS", t: "منزل", s: "Ett stort hus." },
    { w: "US", t: "نحن (عامية)", s: "Oss." },
    { w: "DOKTORN", t: "الطبيب", s: "Doktorn kommer." },
    { w: "DOKTOR", t: "طبيب", s: "En bra doktor." },
    { w: "TOR", t: "جاف/إله", s: "Torrt gräs." },
    { w: "KOR", t: "أبقار", s: "Många kor." },
    { w: "APOTEK", t: "صيدلية", s: "Gå till apoteket." },
    { w: "POT", t: "وعاء (عامية)", s: "En pott." },
    { w: "TE", t: "شاي", s: "Dricka te." },
    { w: "MEDICIN", t: "دواء", s: "Ta medicin." },
    { w: "MED", t: "مع", s: "Kom med mig." },
    { w: "POLISEN", t: "الشرطة", s: "Ring polisen." },
    { w: "POLIS", t: "شرطي", s: "En polis." },
    { w: "BRANDEN", t: "الحريق", s: "Branden är släckt." },
    { w: "BRAND", t: "حريق", s: "Det brinner." },
    { w: "AND", t: "بطة برية", s: "En and i sjön." },
    { w: "DEN", t: "ذاك/الـ", s: "Den bilen." },
    { w: "HJÄLPEN", t: "المساعدة", s: "Tack för hjälpen." },
    { w: "HJÄLP", t: "مساعدة", s: "Ropa på hjälp." },
    { w: "LÄN", t: "محافظة", s: "Stockholms län." },
    { w: "OLYCKA", t: "حادث", s: "En olycka hände." },
    { w: "LYCKA", t: "سعادة", s: "Lycka till." },
    { w: "OCK", t: "أيضاً (قديم)", s: "Ock så vidare." },
    { w: "AL", t: "شجر الحور", s: "En al." },
    { w: "RÄDDA", t: "أنقذ/خائفون", s: "Rädda barnen." },
    { w: "RÄDD", t: "خائف", s: "Jag är rädd." },
    { w: "TRYGG", t: "آمن", s: "Känna sig trygg." },
    { w: "RYGG", t: "ظهر", s: "Ont i ryggen." },
    { w: "TYG", t: "قماش", s: "Ett fint tyg." }
];

// Root words for random generation (Chapters 3+) - Filter for length >= 5 to ensure good puzzles
const WC_ROOT_WORDS = WC_DICTIONARY.filter(item => item.w.length >= 5).map(item => item.w);

console.log(`Word Connect Data Loaded: ${Object.keys(WC_PREDEFINED_LEVELS).length} levels, ${WC_DICTIONARY.length} dictionary words.`);
